/*
 * generated by Xtext 2.10.0
 */
package robotcontrol.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import robotcontrol.ui.internal.RobotcontrolActivator;

public class RocUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RobotcontrolActivator.getInstance().getInjector("robotcontrol.Roc");
	}

}
