/**
 * generated by Xtext 2.10.0
 */
package robot.control.roc;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Movement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link robot.control.roc.Movement#getMotions <em>Motions</em>}</li>
 * </ul>
 *
 * @see robot.control.roc.RocPackage#getMovement()
 * @model
 * @generated
 */
public interface Movement extends EObject
{
  /**
   * Returns the value of the '<em><b>Motions</b></em>' containment reference list.
   * The list contents are of type {@link robot.control.roc.Motion}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Motions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Motions</em>' containment reference list.
   * @see robot.control.roc.RocPackage#getMovement_Motions()
   * @model containment="true"
   * @generated
   */
  EList<Motion> getMotions();

} // Movement
