/**
 * generated by Xtext 2.10.0
 */
package robot.control;

import robot.control.AbstractRocRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RocRuntimeModule extends AbstractRocRuntimeModule {
}
