/*
 * generated by Xtext 2.10.0
 */
package robotcontrol.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class RocGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ProgramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "robotcontrol.Roc.Program");
		private final Assignment cMovementsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cMovementsMovementParserRuleCall_0 = (RuleCall)cMovementsAssignment.eContents().get(0);
		
		//Program hidden(WS, ML_COMMENT, SL_COMMENT):
		//	movements+=Movement*;
		@Override public ParserRule getRule() { return rule; }
		
		//movements+=Movement*
		public Assignment getMovementsAssignment() { return cMovementsAssignment; }
		
		//Movement
		public RuleCall getMovementsMovementParserRuleCall_0() { return cMovementsMovementParserRuleCall_0; }
	}
	public class MovementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "robotcontrol.Roc.Movement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cMotionsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cMotionsMotionParserRuleCall_0_0 = (RuleCall)cMotionsAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final RuleCall cANDTerminalRuleCall_1_0 = (RuleCall)cGroup_1.eContents().get(0);
		private final Assignment cMotionsAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cMotionsMotionParserRuleCall_1_1_0 = (RuleCall)cMotionsAssignment_1_1.eContents().get(0);
		private final RuleCall cPERIODTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//Movement hidden(WS, ML_COMMENT, SL_COMMENT):
		//	motions+=Motion (AND motions+=Motion)* PERIOD;
		@Override public ParserRule getRule() { return rule; }
		
		//motions+=Motion (AND motions+=Motion)* PERIOD
		public Group getGroup() { return cGroup; }
		
		//motions+=Motion
		public Assignment getMotionsAssignment_0() { return cMotionsAssignment_0; }
		
		//Motion
		public RuleCall getMotionsMotionParserRuleCall_0_0() { return cMotionsMotionParserRuleCall_0_0; }
		
		//(AND motions+=Motion)*
		public Group getGroup_1() { return cGroup_1; }
		
		//AND
		public RuleCall getANDTerminalRuleCall_1_0() { return cANDTerminalRuleCall_1_0; }
		
		//motions+=Motion
		public Assignment getMotionsAssignment_1_1() { return cMotionsAssignment_1_1; }
		
		//Motion
		public RuleCall getMotionsMotionParserRuleCall_1_1_0() { return cMotionsMotionParserRuleCall_1_1_0; }
		
		//PERIOD
		public RuleCall getPERIODTerminalRuleCall_2() { return cPERIODTerminalRuleCall_2; }
	}
	public class MotionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "robotcontrol.Roc.Motion");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Assignment cActionAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final RuleCall cActionActionParserRuleCall_0_0_0 = (RuleCall)cActionAssignment_0_0.eContents().get(0);
		private final RuleCall cFORTerminalRuleCall_0_1 = (RuleCall)cGroup_0.eContents().get(1);
		private final Assignment cDurationAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cDurationDURATIONTerminalRuleCall_0_2_0 = (RuleCall)cDurationAssignment_0_2.eContents().get(0);
		private final Assignment cDurationUnitAssignment_0_3 = (Assignment)cGroup_0.eContents().get(3);
		private final RuleCall cDurationUnitDurationUnitEnumRuleCall_0_3_0 = (RuleCall)cDurationUnitAssignment_0_3.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Assignment cActionAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cActionActionParserRuleCall_1_0_0 = (RuleCall)cActionAssignment_1_0.eContents().get(0);
		private final RuleCall cWITHTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Assignment cSpeedAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cSpeedSpeedParserRuleCall_1_2_0 = (RuleCall)cSpeedAssignment_1_2.eContents().get(0);
		private final RuleCall cSPEED_KEYTerminalRuleCall_1_3 = (RuleCall)cGroup_1.eContents().get(3);
		private final Assignment cActionAssignment_2 = (Assignment)cAlternatives.eContents().get(2);
		private final RuleCall cActionActionParserRuleCall_2_0 = (RuleCall)cActionAssignment_2.eContents().get(0);
		
		//Motion:
		//	action=Action FOR duration=DURATION durationUnit=DurationUnit
		//	| action=Action WITH speed=Speed SPEED_KEY
		//	| action=Action;
		@Override public ParserRule getRule() { return rule; }
		
		//action=Action FOR duration=DURATION durationUnit=DurationUnit | action=Action WITH speed=Speed SPEED_KEY | action=Action
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//action=Action FOR duration=DURATION durationUnit=DurationUnit
		public Group getGroup_0() { return cGroup_0; }
		
		//action=Action
		public Assignment getActionAssignment_0_0() { return cActionAssignment_0_0; }
		
		//Action
		public RuleCall getActionActionParserRuleCall_0_0_0() { return cActionActionParserRuleCall_0_0_0; }
		
		//FOR
		public RuleCall getFORTerminalRuleCall_0_1() { return cFORTerminalRuleCall_0_1; }
		
		//duration=DURATION
		public Assignment getDurationAssignment_0_2() { return cDurationAssignment_0_2; }
		
		//DURATION
		public RuleCall getDurationDURATIONTerminalRuleCall_0_2_0() { return cDurationDURATIONTerminalRuleCall_0_2_0; }
		
		//durationUnit=DurationUnit
		public Assignment getDurationUnitAssignment_0_3() { return cDurationUnitAssignment_0_3; }
		
		//DurationUnit
		public RuleCall getDurationUnitDurationUnitEnumRuleCall_0_3_0() { return cDurationUnitDurationUnitEnumRuleCall_0_3_0; }
		
		//action=Action WITH speed=Speed SPEED_KEY
		public Group getGroup_1() { return cGroup_1; }
		
		//action=Action
		public Assignment getActionAssignment_1_0() { return cActionAssignment_1_0; }
		
		//Action
		public RuleCall getActionActionParserRuleCall_1_0_0() { return cActionActionParserRuleCall_1_0_0; }
		
		//WITH
		public RuleCall getWITHTerminalRuleCall_1_1() { return cWITHTerminalRuleCall_1_1; }
		
		//speed=Speed
		public Assignment getSpeedAssignment_1_2() { return cSpeedAssignment_1_2; }
		
		//Speed
		public RuleCall getSpeedSpeedParserRuleCall_1_2_0() { return cSpeedSpeedParserRuleCall_1_2_0; }
		
		//SPEED_KEY
		public RuleCall getSPEED_KEYTerminalRuleCall_1_3() { return cSPEED_KEYTerminalRuleCall_1_3; }
		
		//action=Action
		public Assignment getActionAssignment_2() { return cActionAssignment_2; }
		
		//Action
		public RuleCall getActionActionParserRuleCall_2_0() { return cActionActionParserRuleCall_2_0; }
	}
	public class ActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "robotcontrol.Roc.Action");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cActionHolderAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cActionHolderCompleteActionParserRuleCall_0_0 = (RuleCall)cActionHolderAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Assignment cIntensityAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cIntensityIntensityEnumRuleCall_1_0_0 = (RuleCall)cIntensityAssignment_1_0.eContents().get(0);
		private final Assignment cActionHolderAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cActionHolderSingleActionParserRuleCall_1_1_0 = (RuleCall)cActionHolderAssignment_1_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Assignment cIntensityAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cIntensityIntensityEnumRuleCall_2_0_0 = (RuleCall)cIntensityAssignment_2_0.eContents().get(0);
		private final Assignment cActionHolderAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cActionHolderDirectedActionParserRuleCall_2_1_0 = (RuleCall)cActionHolderAssignment_2_1.eContents().get(0);
		
		//Action:
		//	actionHolder=CompleteAction
		//	| intensity=Intensity? actionHolder=SingleAction
		//	| intensity=Intensity? actionHolder=DirectedAction;
		@Override public ParserRule getRule() { return rule; }
		
		//actionHolder=CompleteAction | intensity=Intensity? actionHolder=SingleAction | intensity=Intensity?
		//actionHolder=DirectedAction
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//actionHolder=CompleteAction
		public Assignment getActionHolderAssignment_0() { return cActionHolderAssignment_0; }
		
		//CompleteAction
		public RuleCall getActionHolderCompleteActionParserRuleCall_0_0() { return cActionHolderCompleteActionParserRuleCall_0_0; }
		
		//intensity=Intensity? actionHolder=SingleAction
		public Group getGroup_1() { return cGroup_1; }
		
		//intensity=Intensity?
		public Assignment getIntensityAssignment_1_0() { return cIntensityAssignment_1_0; }
		
		//Intensity
		public RuleCall getIntensityIntensityEnumRuleCall_1_0_0() { return cIntensityIntensityEnumRuleCall_1_0_0; }
		
		//actionHolder=SingleAction
		public Assignment getActionHolderAssignment_1_1() { return cActionHolderAssignment_1_1; }
		
		//SingleAction
		public RuleCall getActionHolderSingleActionParserRuleCall_1_1_0() { return cActionHolderSingleActionParserRuleCall_1_1_0; }
		
		//intensity=Intensity? actionHolder=DirectedAction
		public Group getGroup_2() { return cGroup_2; }
		
		//intensity=Intensity?
		public Assignment getIntensityAssignment_2_0() { return cIntensityAssignment_2_0; }
		
		//Intensity
		public RuleCall getIntensityIntensityEnumRuleCall_2_0_0() { return cIntensityIntensityEnumRuleCall_2_0_0; }
		
		//actionHolder=DirectedAction
		public Assignment getActionHolderAssignment_2_1() { return cActionHolderAssignment_2_1; }
		
		//DirectedAction
		public RuleCall getActionHolderDirectedActionParserRuleCall_2_1_0() { return cActionHolderDirectedActionParserRuleCall_2_1_0; }
	}
	public class CompleteActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "robotcontrol.Roc.CompleteAction");
		private final Assignment cActionNameAssignment = (Assignment)rule.eContents().get(1);
		private final Keyword cActionNameNeutralFaceKeyword_0 = (Keyword)cActionNameAssignment.eContents().get(0);
		
		//// Actions ------------------------------------------------------------------------
		//CompleteAction:
		//	actionName='neutral face';
		@Override public ParserRule getRule() { return rule; }
		
		//actionName='neutral face'
		public Assignment getActionNameAssignment() { return cActionNameAssignment; }
		
		//'neutral face'
		public Keyword getActionNameNeutralFaceKeyword_0() { return cActionNameNeutralFaceKeyword_0; }
	}
	public class SingleActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "robotcontrol.Roc.SingleAction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cActionNameAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final Keyword cActionNameDropJawKeyword_0_0 = (Keyword)cActionNameAssignment_0.eContents().get(0);
		private final Assignment cActionNameAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final Keyword cActionNameNodHeadKeyword_1_0 = (Keyword)cActionNameAssignment_1.eContents().get(0);
		
		//SingleAction:
		//	actionName='drop jaw'
		//	| actionName='nod head';
		@Override public ParserRule getRule() { return rule; }
		
		//actionName='drop jaw' | actionName='nod head'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//actionName='drop jaw'
		public Assignment getActionNameAssignment_0() { return cActionNameAssignment_0; }
		
		//'drop jaw'
		public Keyword getActionNameDropJawKeyword_0_0() { return cActionNameDropJawKeyword_0_0; }
		
		//actionName='nod head'
		public Assignment getActionNameAssignment_1() { return cActionNameAssignment_1; }
		
		//'nod head'
		public Keyword getActionNameNodHeadKeyword_1_0() { return cActionNameNodHeadKeyword_1_0; }
	}
	public class DirectedActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "robotcontrol.Roc.DirectedAction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Assignment cActionNameAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final RuleCall cActionNameLeftRightDirectedActionParserRuleCall_0_0_0 = (RuleCall)cActionNameAssignment_0_0.eContents().get(0);
		private final Assignment cDirectionAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cDirectionLeftRightDirectionParserRuleCall_0_1_0 = (RuleCall)cDirectionAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Assignment cActionNameAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cActionNameFullDirectedActionParserRuleCall_1_0_0 = (RuleCall)cActionNameAssignment_1_0.eContents().get(0);
		private final Assignment cDirectionAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cDirectionDirectionParserRuleCall_1_1_0 = (RuleCall)cDirectionAssignment_1_1.eContents().get(0);
		
		//DirectedAction:
		//	actionName=LeftRightDirectedAction direction=LeftRightDirection
		//	| actionName=FullDirectedAction direction=Direction;
		@Override public ParserRule getRule() { return rule; }
		
		//actionName=LeftRightDirectedAction direction=LeftRightDirection | actionName=FullDirectedAction direction=Direction
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//actionName=LeftRightDirectedAction direction=LeftRightDirection
		public Group getGroup_0() { return cGroup_0; }
		
		//actionName=LeftRightDirectedAction
		public Assignment getActionNameAssignment_0_0() { return cActionNameAssignment_0_0; }
		
		//LeftRightDirectedAction
		public RuleCall getActionNameLeftRightDirectedActionParserRuleCall_0_0_0() { return cActionNameLeftRightDirectedActionParserRuleCall_0_0_0; }
		
		//direction=LeftRightDirection
		public Assignment getDirectionAssignment_0_1() { return cDirectionAssignment_0_1; }
		
		//LeftRightDirection
		public RuleCall getDirectionLeftRightDirectionParserRuleCall_0_1_0() { return cDirectionLeftRightDirectionParserRuleCall_0_1_0; }
		
		//actionName=FullDirectedAction direction=Direction
		public Group getGroup_1() { return cGroup_1; }
		
		//actionName=FullDirectedAction
		public Assignment getActionNameAssignment_1_0() { return cActionNameAssignment_1_0; }
		
		//FullDirectedAction
		public RuleCall getActionNameFullDirectedActionParserRuleCall_1_0_0() { return cActionNameFullDirectedActionParserRuleCall_1_0_0; }
		
		//direction=Direction
		public Assignment getDirectionAssignment_1_1() { return cDirectionAssignment_1_1; }
		
		//Direction
		public RuleCall getDirectionDirectionParserRuleCall_1_1_0() { return cDirectionDirectionParserRuleCall_1_1_0; }
	}
	public class LeftRightDirectedActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "robotcontrol.Roc.LeftRightDirectedAction");
		private final Assignment cTiltHeadAssignment = (Assignment)rule.eContents().get(1);
		private final Keyword cTiltHeadTiltHeadKeyword_0 = (Keyword)cTiltHeadAssignment.eContents().get(0);
		
		//LeftRightDirectedAction:
		//	tiltHead='tilt head';
		@Override public ParserRule getRule() { return rule; }
		
		//tiltHead='tilt head'
		public Assignment getTiltHeadAssignment() { return cTiltHeadAssignment; }
		
		//'tilt head'
		public Keyword getTiltHeadTiltHeadKeyword_0() { return cTiltHeadTiltHeadKeyword_0; }
	}
	public class LeftRightDirectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "robotcontrol.Roc.LeftRightDirection");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cLeftAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final Keyword cLeftLeftKeyword_0_0 = (Keyword)cLeftAssignment_0.eContents().get(0);
		private final Assignment cRightAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final Keyword cRightRightKeyword_1_0 = (Keyword)cRightAssignment_1.eContents().get(0);
		
		//LeftRightDirection:
		//	left='left'
		//	| right='right';
		@Override public ParserRule getRule() { return rule; }
		
		//left='left' | right='right'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//left='left'
		public Assignment getLeftAssignment_0() { return cLeftAssignment_0; }
		
		//'left'
		public Keyword getLeftLeftKeyword_0_0() { return cLeftLeftKeyword_0_0; }
		
		//right='right'
		public Assignment getRightAssignment_1() { return cRightAssignment_1; }
		
		//'right'
		public Keyword getRightRightKeyword_1_0() { return cRightRightKeyword_1_0; }
	}
	public class FullDirectedActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "robotcontrol.Roc.FullDirectedAction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cTurnHeadAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final Keyword cTurnHeadTurnHeadKeyword_0_0 = (Keyword)cTurnHeadAssignment_0.eContents().get(0);
		private final Assignment cTurnEyesAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final Keyword cTurnEyesTurnEyesKeyword_1_0 = (Keyword)cTurnEyesAssignment_1.eContents().get(0);
		
		//FullDirectedAction:
		//	turnHead='turn head'
		//	| turnEyes='turn eyes';
		@Override public ParserRule getRule() { return rule; }
		
		//turnHead='turn head' | turnEyes='turn eyes'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//turnHead='turn head'
		public Assignment getTurnHeadAssignment_0() { return cTurnHeadAssignment_0; }
		
		//'turn head'
		public Keyword getTurnHeadTurnHeadKeyword_0_0() { return cTurnHeadTurnHeadKeyword_0_0; }
		
		//turnEyes='turn eyes'
		public Assignment getTurnEyesAssignment_1() { return cTurnEyesAssignment_1; }
		
		//'turn eyes'
		public Keyword getTurnEyesTurnEyesKeyword_1_0() { return cTurnEyesTurnEyesKeyword_1_0; }
	}
	public class DirectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "robotcontrol.Roc.Direction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cUPAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final Keyword cUPUpKeyword_0_0 = (Keyword)cUPAssignment_0.eContents().get(0);
		private final Assignment cDOWNAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final Keyword cDOWNDownKeyword_1_0 = (Keyword)cDOWNAssignment_1.eContents().get(0);
		private final Assignment cLEFTAssignment_2 = (Assignment)cAlternatives.eContents().get(2);
		private final Keyword cLEFTLeftKeyword_2_0 = (Keyword)cLEFTAssignment_2.eContents().get(0);
		private final Assignment cRIGHTAssignment_3 = (Assignment)cAlternatives.eContents().get(3);
		private final Keyword cRIGHTRightKeyword_3_0 = (Keyword)cRIGHTAssignment_3.eContents().get(0);
		
		//Direction:
		//	UP='up'
		//	| DOWN='down'
		//	| LEFT='left'
		//	| RIGHT='right';
		@Override public ParserRule getRule() { return rule; }
		
		//UP='up' | DOWN='down' | LEFT='left' | RIGHT='right'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//UP='up'
		public Assignment getUPAssignment_0() { return cUPAssignment_0; }
		
		//'up'
		public Keyword getUPUpKeyword_0_0() { return cUPUpKeyword_0_0; }
		
		//DOWN='down'
		public Assignment getDOWNAssignment_1() { return cDOWNAssignment_1; }
		
		//'down'
		public Keyword getDOWNDownKeyword_1_0() { return cDOWNDownKeyword_1_0; }
		
		//LEFT='left'
		public Assignment getLEFTAssignment_2() { return cLEFTAssignment_2; }
		
		//'left'
		public Keyword getLEFTLeftKeyword_2_0() { return cLEFTLeftKeyword_2_0; }
		
		//RIGHT='right'
		public Assignment getRIGHTAssignment_3() { return cRIGHTAssignment_3; }
		
		//'right'
		public Keyword getRIGHTRightKeyword_3_0() { return cRIGHTRightKeyword_3_0; }
	}
	public class SpeedElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "robotcontrol.Roc.Speed");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cSLOWESTAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final Keyword cSLOWESTSlowestKeyword_0_0 = (Keyword)cSLOWESTAssignment_0.eContents().get(0);
		private final Assignment cSLOWAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final Keyword cSLOWSlowKeyword_1_0 = (Keyword)cSLOWAssignment_1.eContents().get(0);
		private final Assignment cNORMALAssignment_2 = (Assignment)cAlternatives.eContents().get(2);
		private final Keyword cNORMALNormalKeyword_2_0 = (Keyword)cNORMALAssignment_2.eContents().get(0);
		private final Assignment cFASTAssignment_3 = (Assignment)cAlternatives.eContents().get(3);
		private final Keyword cFASTFastKeyword_3_0 = (Keyword)cFASTAssignment_3.eContents().get(0);
		private final Assignment cFULLAssignment_4 = (Assignment)cAlternatives.eContents().get(4);
		private final Keyword cFULLFullKeyword_4_0 = (Keyword)cFULLAssignment_4.eContents().get(0);
		
		//Speed:
		//	SLOWEST='slowest'
		//	| SLOW='slow'
		//	| NORMAL='normal'
		//	| FAST='fast'
		//	| FULL='full';
		@Override public ParserRule getRule() { return rule; }
		
		//SLOWEST='slowest' | SLOW='slow' | NORMAL='normal' | FAST='fast' | FULL='full'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//SLOWEST='slowest'
		public Assignment getSLOWESTAssignment_0() { return cSLOWESTAssignment_0; }
		
		//'slowest'
		public Keyword getSLOWESTSlowestKeyword_0_0() { return cSLOWESTSlowestKeyword_0_0; }
		
		//SLOW='slow'
		public Assignment getSLOWAssignment_1() { return cSLOWAssignment_1; }
		
		//'slow'
		public Keyword getSLOWSlowKeyword_1_0() { return cSLOWSlowKeyword_1_0; }
		
		//NORMAL='normal'
		public Assignment getNORMALAssignment_2() { return cNORMALAssignment_2; }
		
		//'normal'
		public Keyword getNORMALNormalKeyword_2_0() { return cNORMALNormalKeyword_2_0; }
		
		//FAST='fast'
		public Assignment getFASTAssignment_3() { return cFASTAssignment_3; }
		
		//'fast'
		public Keyword getFASTFastKeyword_3_0() { return cFASTFastKeyword_3_0; }
		
		//FULL='full'
		public Assignment getFULLAssignment_4() { return cFULLAssignment_4; }
		
		//'full'
		public Keyword getFULLFullKeyword_4_0() { return cFULLFullKeyword_4_0; }
	}
	
	public class IntensityElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "robotcontrol.Roc.Intensity");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cCEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cCPronouncedKeyword_0_0 = (Keyword)cCEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cAEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cATraceOfKeyword_1_0 = (Keyword)cAEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cBEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cBSlightlyKeyword_2_0 = (Keyword)cBEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cDEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cDSevereKeyword_3_0 = (Keyword)cDEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cEEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cEMaximumKeyword_4_0 = (Keyword)cEEnumLiteralDeclaration_4.eContents().get(0);
		
		//enum Intensity:
		//	C='pronounced' // First position is used as default value
		//	| A='trace of'
		//	| B='slightly'
		//	| D='severe'
		//	| E='maximum';
		public EnumRule getRule() { return rule; }
		
		//C='pronounced' // First position is used as default value
		//| A='trace of' | B='slightly' | D='severe' | E='maximum'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//C='pronounced'
		public EnumLiteralDeclaration getCEnumLiteralDeclaration_0() { return cCEnumLiteralDeclaration_0; }
		
		//'pronounced'
		public Keyword getCPronouncedKeyword_0_0() { return cCPronouncedKeyword_0_0; }
		
		//A='trace of'
		public EnumLiteralDeclaration getAEnumLiteralDeclaration_1() { return cAEnumLiteralDeclaration_1; }
		
		//'trace of'
		public Keyword getATraceOfKeyword_1_0() { return cATraceOfKeyword_1_0; }
		
		//B='slightly'
		public EnumLiteralDeclaration getBEnumLiteralDeclaration_2() { return cBEnumLiteralDeclaration_2; }
		
		//'slightly'
		public Keyword getBSlightlyKeyword_2_0() { return cBSlightlyKeyword_2_0; }
		
		//D='severe'
		public EnumLiteralDeclaration getDEnumLiteralDeclaration_3() { return cDEnumLiteralDeclaration_3; }
		
		//'severe'
		public Keyword getDSevereKeyword_3_0() { return cDSevereKeyword_3_0; }
		
		//E='maximum'
		public EnumLiteralDeclaration getEEnumLiteralDeclaration_4() { return cEEnumLiteralDeclaration_4; }
		
		//'maximum'
		public Keyword getEMaximumKeyword_4_0() { return cEMaximumKeyword_4_0; }
	}
	public class DurationUnitElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "robotcontrol.Roc.DurationUnit");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cMILLISECONDSEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cMILLISECONDSMillisecondsKeyword_0_0 = (Keyword)cMILLISECONDSEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cSECONDSEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cSECONDSSecondsKeyword_1_0 = (Keyword)cSECONDSEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cMINUTESEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cMINUTESMinutesKeyword_2_0 = (Keyword)cMINUTESEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum DurationUnit:
		//	MILLISECONDS='milliseconds'
		//	| SECONDS='seconds'
		//	| MINUTES='minutes';
		public EnumRule getRule() { return rule; }
		
		//MILLISECONDS='milliseconds' | SECONDS='seconds' | MINUTES='minutes'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//MILLISECONDS='milliseconds'
		public EnumLiteralDeclaration getMILLISECONDSEnumLiteralDeclaration_0() { return cMILLISECONDSEnumLiteralDeclaration_0; }
		
		//'milliseconds'
		public Keyword getMILLISECONDSMillisecondsKeyword_0_0() { return cMILLISECONDSMillisecondsKeyword_0_0; }
		
		//SECONDS='seconds'
		public EnumLiteralDeclaration getSECONDSEnumLiteralDeclaration_1() { return cSECONDSEnumLiteralDeclaration_1; }
		
		//'seconds'
		public Keyword getSECONDSSecondsKeyword_1_0() { return cSECONDSSecondsKeyword_1_0; }
		
		//MINUTES='minutes'
		public EnumLiteralDeclaration getMINUTESEnumLiteralDeclaration_2() { return cMINUTESEnumLiteralDeclaration_2; }
		
		//'minutes'
		public Keyword getMINUTESMinutesKeyword_2_0() { return cMINUTESMinutesKeyword_2_0; }
	}
	
	private final ProgramElements pProgram;
	private final MovementElements pMovement;
	private final MotionElements pMotion;
	private final ActionElements pAction;
	private final IntensityElements eIntensity;
	private final CompleteActionElements pCompleteAction;
	private final SingleActionElements pSingleAction;
	private final DirectedActionElements pDirectedAction;
	private final LeftRightDirectedActionElements pLeftRightDirectedAction;
	private final LeftRightDirectionElements pLeftRightDirection;
	private final FullDirectedActionElements pFullDirectedAction;
	private final DirectionElements pDirection;
	private final SpeedElements pSpeed;
	private final TerminalRule tDURATION;
	private final DurationUnitElements eDurationUnit;
	private final TerminalRule tFOR;
	private final TerminalRule tWITH;
	private final TerminalRule tSPEED_KEY;
	private final TerminalRule tAND;
	private final TerminalRule tPERIOD;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public RocGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pProgram = new ProgramElements();
		this.pMovement = new MovementElements();
		this.pMotion = new MotionElements();
		this.pAction = new ActionElements();
		this.eIntensity = new IntensityElements();
		this.pCompleteAction = new CompleteActionElements();
		this.pSingleAction = new SingleActionElements();
		this.pDirectedAction = new DirectedActionElements();
		this.pLeftRightDirectedAction = new LeftRightDirectedActionElements();
		this.pLeftRightDirection = new LeftRightDirectionElements();
		this.pFullDirectedAction = new FullDirectedActionElements();
		this.pDirection = new DirectionElements();
		this.pSpeed = new SpeedElements();
		this.tDURATION = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "robotcontrol.Roc.DURATION");
		this.eDurationUnit = new DurationUnitElements();
		this.tFOR = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "robotcontrol.Roc.FOR");
		this.tWITH = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "robotcontrol.Roc.WITH");
		this.tSPEED_KEY = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "robotcontrol.Roc.SPEED_KEY");
		this.tAND = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "robotcontrol.Roc.AND");
		this.tPERIOD = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "robotcontrol.Roc.PERIOD");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("robotcontrol.Roc".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Program hidden(WS, ML_COMMENT, SL_COMMENT):
	//	movements+=Movement*;
	public ProgramElements getProgramAccess() {
		return pProgram;
	}
	
	public ParserRule getProgramRule() {
		return getProgramAccess().getRule();
	}
	
	//Movement hidden(WS, ML_COMMENT, SL_COMMENT):
	//	motions+=Motion (AND motions+=Motion)* PERIOD;
	public MovementElements getMovementAccess() {
		return pMovement;
	}
	
	public ParserRule getMovementRule() {
		return getMovementAccess().getRule();
	}
	
	//Motion:
	//	action=Action FOR duration=DURATION durationUnit=DurationUnit
	//	| action=Action WITH speed=Speed SPEED_KEY
	//	| action=Action;
	public MotionElements getMotionAccess() {
		return pMotion;
	}
	
	public ParserRule getMotionRule() {
		return getMotionAccess().getRule();
	}
	
	//Action:
	//	actionHolder=CompleteAction
	//	| intensity=Intensity? actionHolder=SingleAction
	//	| intensity=Intensity? actionHolder=DirectedAction;
	public ActionElements getActionAccess() {
		return pAction;
	}
	
	public ParserRule getActionRule() {
		return getActionAccess().getRule();
	}
	
	//enum Intensity:
	//	C='pronounced' // First position is used as default value
	//	| A='trace of'
	//	| B='slightly'
	//	| D='severe'
	//	| E='maximum';
	public IntensityElements getIntensityAccess() {
		return eIntensity;
	}
	
	public EnumRule getIntensityRule() {
		return getIntensityAccess().getRule();
	}
	
	//// Actions ------------------------------------------------------------------------
	//CompleteAction:
	//	actionName='neutral face';
	public CompleteActionElements getCompleteActionAccess() {
		return pCompleteAction;
	}
	
	public ParserRule getCompleteActionRule() {
		return getCompleteActionAccess().getRule();
	}
	
	//SingleAction:
	//	actionName='drop jaw'
	//	| actionName='nod head';
	public SingleActionElements getSingleActionAccess() {
		return pSingleAction;
	}
	
	public ParserRule getSingleActionRule() {
		return getSingleActionAccess().getRule();
	}
	
	//DirectedAction:
	//	actionName=LeftRightDirectedAction direction=LeftRightDirection
	//	| actionName=FullDirectedAction direction=Direction;
	public DirectedActionElements getDirectedActionAccess() {
		return pDirectedAction;
	}
	
	public ParserRule getDirectedActionRule() {
		return getDirectedActionAccess().getRule();
	}
	
	//LeftRightDirectedAction:
	//	tiltHead='tilt head';
	public LeftRightDirectedActionElements getLeftRightDirectedActionAccess() {
		return pLeftRightDirectedAction;
	}
	
	public ParserRule getLeftRightDirectedActionRule() {
		return getLeftRightDirectedActionAccess().getRule();
	}
	
	//LeftRightDirection:
	//	left='left'
	//	| right='right';
	public LeftRightDirectionElements getLeftRightDirectionAccess() {
		return pLeftRightDirection;
	}
	
	public ParserRule getLeftRightDirectionRule() {
		return getLeftRightDirectionAccess().getRule();
	}
	
	//FullDirectedAction:
	//	turnHead='turn head'
	//	| turnEyes='turn eyes';
	public FullDirectedActionElements getFullDirectedActionAccess() {
		return pFullDirectedAction;
	}
	
	public ParserRule getFullDirectedActionRule() {
		return getFullDirectedActionAccess().getRule();
	}
	
	//Direction:
	//	UP='up'
	//	| DOWN='down'
	//	| LEFT='left'
	//	| RIGHT='right';
	public DirectionElements getDirectionAccess() {
		return pDirection;
	}
	
	public ParserRule getDirectionRule() {
		return getDirectionAccess().getRule();
	}
	
	//Speed:
	//	SLOWEST='slowest'
	//	| SLOW='slow'
	//	| NORMAL='normal'
	//	| FAST='fast'
	//	| FULL='full';
	public SpeedElements getSpeedAccess() {
		return pSpeed;
	}
	
	public ParserRule getSpeedRule() {
		return getSpeedAccess().getRule();
	}
	
	//terminal DURATION:
	//	INT;
	public TerminalRule getDURATIONRule() {
		return tDURATION;
	}
	
	//enum DurationUnit:
	//	MILLISECONDS='milliseconds'
	//	| SECONDS='seconds'
	//	| MINUTES='minutes';
	public DurationUnitElements getDurationUnitAccess() {
		return eDurationUnit;
	}
	
	public EnumRule getDurationUnitRule() {
		return getDurationUnitAccess().getRule();
	}
	
	//terminal FOR:
	//	'for';
	public TerminalRule getFORRule() {
		return tFOR;
	}
	
	//terminal WITH:
	//	'with';
	public TerminalRule getWITHRule() {
		return tWITH;
	}
	
	//terminal SPEED_KEY:
	//	'speed';
	public TerminalRule getSPEED_KEYRule() {
		return tSPEED_KEY;
	}
	
	//terminal AND:
	//	'and';
	public TerminalRule getANDRule() {
		return tAND;
	}
	
	//terminal PERIOD:
	//	'.';
	public TerminalRule getPERIODRule() {
		return tPERIOD;
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
