/*
 * generated by Xtext 2.10.0
 */
package robot.control.idea.highlighting;

import com.intellij.openapi.fileTypes.SingleLazyInstanceSyntaxHighlighterFactory;
import com.intellij.openapi.fileTypes.SyntaxHighlighter;
import org.jetbrains.annotations.NotNull;
import robot.control.idea.lang.RocLanguage;

public class RocSyntaxHighlighterFactory extends SingleLazyInstanceSyntaxHighlighterFactory {
	
	@Override
	@NotNull
	protected SyntaxHighlighter createHighlighter() {
		return RocLanguage.INSTANCE.getInstance(SyntaxHighlighter.class);
	}
}
