/*
 * generated by Xtext 2.10.0
 */
package robot.control.idea.highlighting;

import org.eclipse.xtext.idea.highlighting.SemanticHighlightVisitor;
import robot.control.idea.lang.RocLanguage;

public class RocSemanticHighlightVisitor extends SemanticHighlightVisitor {
	public RocSemanticHighlightVisitor() {
		RocLanguage.INSTANCE.injectMembers(this);
	}
}
