/*
 * generated by Xtext 2.10.0
 */
package robotcontrol.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRocScopeProvider extends DelegatingScopeProvider {
}
