/*
 * generated by Xtext 2.10.0
 */
package robot.control.idea.lang.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RocAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("robot/control/idea/parser/antlr/internal/PsiInternalRoc.tokens");
	}
}
