/*
 * generated by Xtext 2.10.0
 */
package robot.control.idea.completion

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage
import robot.control.idea.lang.RocLanguage

class RocCompletionContributor extends AbstractRocCompletionContributor {
	new() {
		this(RocLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
