/*
 * generated by Xtext 2.10.0
 */
package robot.control.idea.facet;

import com.intellij.facet.Facet;
import com.intellij.facet.FacetTypeId;
import org.eclipse.xtext.idea.facet.AbstractFacetType;
import robot.control.idea.lang.RocLanguage;

public class RocFacetType extends AbstractFacetType<RocFacetConfiguration> {

	public static final FacetTypeId<Facet<RocFacetConfiguration>> TYPEID = new FacetTypeId<Facet<RocFacetConfiguration>>("robot.control.Roc");

	public RocFacetType() {
		super(TYPEID, "robot.control.Roc", "Roc");
		RocLanguage.INSTANCE.injectMembers(this);
	}
}
