/*
 * generated by Xtext 2.10.0
 */
package robot.control.idea.lang;

import com.intellij.psi.tree.IFileElementType;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.idea.lang.IElementTypeProvider;
import org.eclipse.xtext.psi.stubs.XtextFileElementType;
import org.eclipse.xtext.psi.stubs.XtextFileStub;
import org.eclipse.xtext.psi.tree.IGrammarAwareElementType;
import robot.control.idea.lang.psi.impl.RocFileImpl;
import robot.control.services.RocGrammarAccess;

public class RocElementTypeProvider implements IElementTypeProvider {

	public static final IFileElementType FILE_TYPE = new XtextFileElementType<XtextFileStub<RocFileImpl>>(RocLanguage.INSTANCE);

	private static final Map<EObject, IGrammarAwareElementType> GRAMMAR_ELEMENT_TYPE = new HashMap<EObject, IGrammarAwareElementType>();

	private static IGrammarAwareElementType associate(IGrammarAwareElementType grammarAwareElementType) {
		GRAMMAR_ELEMENT_TYPE.put(grammarAwareElementType.getGrammarElement(), grammarAwareElementType);
		return grammarAwareElementType;
	}

	private static final RocGrammarAccess GRAMMAR_ACCESS = RocLanguage.INSTANCE.getInstance(RocGrammarAccess.class);

	private static class ProgramFactory {
		public static IGrammarAwareElementType createProgramElementType() {
			return new IGrammarAwareElementType("Program_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getProgramRule());
		}
		public static IGrammarAwareElementType createProgram_MovementsAssignmentElementType() {
			return new IGrammarAwareElementType("Program_MovementsAssignment_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getProgramAccess().getMovementsAssignment());
		}
		public static IGrammarAwareElementType createProgram_MovementsMovementParserRuleCall_0ElementType() {
			return new IGrammarAwareElementType("Program_MovementsMovementParserRuleCall_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getProgramAccess().getMovementsMovementParserRuleCall_0());
		}
	}

	public static final IGrammarAwareElementType Program_ELEMENT_TYPE = associate(ProgramFactory.createProgramElementType());

	public static final IGrammarAwareElementType Program_MovementsAssignment_ELEMENT_TYPE = associate(ProgramFactory.createProgram_MovementsAssignmentElementType());

	public static final IGrammarAwareElementType Program_MovementsMovementParserRuleCall_0_ELEMENT_TYPE = associate(ProgramFactory.createProgram_MovementsMovementParserRuleCall_0ElementType());

	private static class MovementFactory {
		public static IGrammarAwareElementType createMovementElementType() {
			return new IGrammarAwareElementType("Movement_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getMovementRule());
		}
		public static IGrammarAwareElementType createMovement_GroupElementType() {
			return new IGrammarAwareElementType("Movement_Group_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getMovementAccess().getGroup());
		}
		public static IGrammarAwareElementType createMovement_MotionsAssignment_0ElementType() {
			return new IGrammarAwareElementType("Movement_MotionsAssignment_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getMovementAccess().getMotionsAssignment_0());
		}
		public static IGrammarAwareElementType createMovement_MotionsMotionParserRuleCall_0_0ElementType() {
			return new IGrammarAwareElementType("Movement_MotionsMotionParserRuleCall_0_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getMovementAccess().getMotionsMotionParserRuleCall_0_0());
		}
		public static IGrammarAwareElementType createMovement_Group_1ElementType() {
			return new IGrammarAwareElementType("Movement_Group_1_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getMovementAccess().getGroup_1());
		}
		public static IGrammarAwareElementType createMovement_ANDTerminalRuleCall_1_0ElementType() {
			return new IGrammarAwareElementType("Movement_ANDTerminalRuleCall_1_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getMovementAccess().getANDTerminalRuleCall_1_0());
		}
		public static IGrammarAwareElementType createMovement_MotionsAssignment_1_1ElementType() {
			return new IGrammarAwareElementType("Movement_MotionsAssignment_1_1_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getMovementAccess().getMotionsAssignment_1_1());
		}
		public static IGrammarAwareElementType createMovement_MotionsMotionParserRuleCall_1_1_0ElementType() {
			return new IGrammarAwareElementType("Movement_MotionsMotionParserRuleCall_1_1_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getMovementAccess().getMotionsMotionParserRuleCall_1_1_0());
		}
		public static IGrammarAwareElementType createMovement_PERIODTerminalRuleCall_2ElementType() {
			return new IGrammarAwareElementType("Movement_PERIODTerminalRuleCall_2_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getMovementAccess().getPERIODTerminalRuleCall_2());
		}
	}

	public static final IGrammarAwareElementType Movement_ELEMENT_TYPE = associate(MovementFactory.createMovementElementType());

	public static final IGrammarAwareElementType Movement_Group_ELEMENT_TYPE = associate(MovementFactory.createMovement_GroupElementType());

	public static final IGrammarAwareElementType Movement_MotionsAssignment_0_ELEMENT_TYPE = associate(MovementFactory.createMovement_MotionsAssignment_0ElementType());

	public static final IGrammarAwareElementType Movement_MotionsMotionParserRuleCall_0_0_ELEMENT_TYPE = associate(MovementFactory.createMovement_MotionsMotionParserRuleCall_0_0ElementType());

	public static final IGrammarAwareElementType Movement_Group_1_ELEMENT_TYPE = associate(MovementFactory.createMovement_Group_1ElementType());

	public static final IGrammarAwareElementType Movement_ANDTerminalRuleCall_1_0_ELEMENT_TYPE = associate(MovementFactory.createMovement_ANDTerminalRuleCall_1_0ElementType());

	public static final IGrammarAwareElementType Movement_MotionsAssignment_1_1_ELEMENT_TYPE = associate(MovementFactory.createMovement_MotionsAssignment_1_1ElementType());

	public static final IGrammarAwareElementType Movement_MotionsMotionParserRuleCall_1_1_0_ELEMENT_TYPE = associate(MovementFactory.createMovement_MotionsMotionParserRuleCall_1_1_0ElementType());

	public static final IGrammarAwareElementType Movement_PERIODTerminalRuleCall_2_ELEMENT_TYPE = associate(MovementFactory.createMovement_PERIODTerminalRuleCall_2ElementType());

	private static class MotionFactory {
		public static IGrammarAwareElementType createMotionElementType() {
			return new IGrammarAwareElementType("Motion_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getMotionRule());
		}
		public static IGrammarAwareElementType createMotion_GroupElementType() {
			return new IGrammarAwareElementType("Motion_Group_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getMotionAccess().getGroup());
		}
		public static IGrammarAwareElementType createMotion_ActionAssignment_0ElementType() {
			return new IGrammarAwareElementType("Motion_ActionAssignment_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getMotionAccess().getActionAssignment_0());
		}
		public static IGrammarAwareElementType createMotion_ActionActionParserRuleCall_0_0ElementType() {
			return new IGrammarAwareElementType("Motion_ActionActionParserRuleCall_0_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getMotionAccess().getActionActionParserRuleCall_0_0());
		}
		public static IGrammarAwareElementType createMotion_FORTerminalRuleCall_1ElementType() {
			return new IGrammarAwareElementType("Motion_FORTerminalRuleCall_1_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getMotionAccess().getFORTerminalRuleCall_1());
		}
		public static IGrammarAwareElementType createMotion_DurationAssignment_2ElementType() {
			return new IGrammarAwareElementType("Motion_DurationAssignment_2_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getMotionAccess().getDurationAssignment_2());
		}
		public static IGrammarAwareElementType createMotion_DurationDurationTerminalRuleCall_2_0ElementType() {
			return new IGrammarAwareElementType("Motion_DurationDurationTerminalRuleCall_2_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getMotionAccess().getDurationDurationTerminalRuleCall_2_0());
		}
		public static IGrammarAwareElementType createMotion_DurationUnitAssignment_3ElementType() {
			return new IGrammarAwareElementType("Motion_DurationUnitAssignment_3_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getMotionAccess().getDurationUnitAssignment_3());
		}
		public static IGrammarAwareElementType createMotion_DurationUnitDurationUnitEnumRuleCall_3_0ElementType() {
			return new IGrammarAwareElementType("Motion_DurationUnitDurationUnitEnumRuleCall_3_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getMotionAccess().getDurationUnitDurationUnitEnumRuleCall_3_0());
		}
	}

	public static final IGrammarAwareElementType Motion_ELEMENT_TYPE = associate(MotionFactory.createMotionElementType());

	public static final IGrammarAwareElementType Motion_Group_ELEMENT_TYPE = associate(MotionFactory.createMotion_GroupElementType());

	public static final IGrammarAwareElementType Motion_ActionAssignment_0_ELEMENT_TYPE = associate(MotionFactory.createMotion_ActionAssignment_0ElementType());

	public static final IGrammarAwareElementType Motion_ActionActionParserRuleCall_0_0_ELEMENT_TYPE = associate(MotionFactory.createMotion_ActionActionParserRuleCall_0_0ElementType());

	public static final IGrammarAwareElementType Motion_FORTerminalRuleCall_1_ELEMENT_TYPE = associate(MotionFactory.createMotion_FORTerminalRuleCall_1ElementType());

	public static final IGrammarAwareElementType Motion_DurationAssignment_2_ELEMENT_TYPE = associate(MotionFactory.createMotion_DurationAssignment_2ElementType());

	public static final IGrammarAwareElementType Motion_DurationDurationTerminalRuleCall_2_0_ELEMENT_TYPE = associate(MotionFactory.createMotion_DurationDurationTerminalRuleCall_2_0ElementType());

	public static final IGrammarAwareElementType Motion_DurationUnitAssignment_3_ELEMENT_TYPE = associate(MotionFactory.createMotion_DurationUnitAssignment_3ElementType());

	public static final IGrammarAwareElementType Motion_DurationUnitDurationUnitEnumRuleCall_3_0_ELEMENT_TYPE = associate(MotionFactory.createMotion_DurationUnitDurationUnitEnumRuleCall_3_0ElementType());

	private static class ActionFactory {
		public static IGrammarAwareElementType createActionElementType() {
			return new IGrammarAwareElementType("Action_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getActionRule());
		}
		public static IGrammarAwareElementType createAction_AlternativesElementType() {
			return new IGrammarAwareElementType("Action_Alternatives_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getActionAccess().getAlternatives());
		}
		public static IGrammarAwareElementType createAction_ActionHolderAssignment_0ElementType() {
			return new IGrammarAwareElementType("Action_ActionHolderAssignment_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getActionAccess().getActionHolderAssignment_0());
		}
		public static IGrammarAwareElementType createAction_ActionHolderCompleteActionParserRuleCall_0_0ElementType() {
			return new IGrammarAwareElementType("Action_ActionHolderCompleteActionParserRuleCall_0_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getActionAccess().getActionHolderCompleteActionParserRuleCall_0_0());
		}
		public static IGrammarAwareElementType createAction_Group_1ElementType() {
			return new IGrammarAwareElementType("Action_Group_1_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getActionAccess().getGroup_1());
		}
		public static IGrammarAwareElementType createAction_IntensityAssignment_1_0ElementType() {
			return new IGrammarAwareElementType("Action_IntensityAssignment_1_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getActionAccess().getIntensityAssignment_1_0());
		}
		public static IGrammarAwareElementType createAction_IntensityIntensityEnumRuleCall_1_0_0ElementType() {
			return new IGrammarAwareElementType("Action_IntensityIntensityEnumRuleCall_1_0_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getActionAccess().getIntensityIntensityEnumRuleCall_1_0_0());
		}
		public static IGrammarAwareElementType createAction_ActionHolderAssignment_1_1ElementType() {
			return new IGrammarAwareElementType("Action_ActionHolderAssignment_1_1_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getActionAccess().getActionHolderAssignment_1_1());
		}
		public static IGrammarAwareElementType createAction_ActionHolderSingleActionParserRuleCall_1_1_0ElementType() {
			return new IGrammarAwareElementType("Action_ActionHolderSingleActionParserRuleCall_1_1_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getActionAccess().getActionHolderSingleActionParserRuleCall_1_1_0());
		}
		public static IGrammarAwareElementType createAction_Group_2ElementType() {
			return new IGrammarAwareElementType("Action_Group_2_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getActionAccess().getGroup_2());
		}
		public static IGrammarAwareElementType createAction_IntensityAssignment_2_0ElementType() {
			return new IGrammarAwareElementType("Action_IntensityAssignment_2_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getActionAccess().getIntensityAssignment_2_0());
		}
		public static IGrammarAwareElementType createAction_IntensityIntensityEnumRuleCall_2_0_0ElementType() {
			return new IGrammarAwareElementType("Action_IntensityIntensityEnumRuleCall_2_0_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getActionAccess().getIntensityIntensityEnumRuleCall_2_0_0());
		}
		public static IGrammarAwareElementType createAction_ActionHolderAssignment_2_1ElementType() {
			return new IGrammarAwareElementType("Action_ActionHolderAssignment_2_1_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getActionAccess().getActionHolderAssignment_2_1());
		}
		public static IGrammarAwareElementType createAction_ActionHolderDirectedActionParserRuleCall_2_1_0ElementType() {
			return new IGrammarAwareElementType("Action_ActionHolderDirectedActionParserRuleCall_2_1_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getActionAccess().getActionHolderDirectedActionParserRuleCall_2_1_0());
		}
	}

	public static final IGrammarAwareElementType Action_ELEMENT_TYPE = associate(ActionFactory.createActionElementType());

	public static final IGrammarAwareElementType Action_Alternatives_ELEMENT_TYPE = associate(ActionFactory.createAction_AlternativesElementType());

	public static final IGrammarAwareElementType Action_ActionHolderAssignment_0_ELEMENT_TYPE = associate(ActionFactory.createAction_ActionHolderAssignment_0ElementType());

	public static final IGrammarAwareElementType Action_ActionHolderCompleteActionParserRuleCall_0_0_ELEMENT_TYPE = associate(ActionFactory.createAction_ActionHolderCompleteActionParserRuleCall_0_0ElementType());

	public static final IGrammarAwareElementType Action_Group_1_ELEMENT_TYPE = associate(ActionFactory.createAction_Group_1ElementType());

	public static final IGrammarAwareElementType Action_IntensityAssignment_1_0_ELEMENT_TYPE = associate(ActionFactory.createAction_IntensityAssignment_1_0ElementType());

	public static final IGrammarAwareElementType Action_IntensityIntensityEnumRuleCall_1_0_0_ELEMENT_TYPE = associate(ActionFactory.createAction_IntensityIntensityEnumRuleCall_1_0_0ElementType());

	public static final IGrammarAwareElementType Action_ActionHolderAssignment_1_1_ELEMENT_TYPE = associate(ActionFactory.createAction_ActionHolderAssignment_1_1ElementType());

	public static final IGrammarAwareElementType Action_ActionHolderSingleActionParserRuleCall_1_1_0_ELEMENT_TYPE = associate(ActionFactory.createAction_ActionHolderSingleActionParserRuleCall_1_1_0ElementType());

	public static final IGrammarAwareElementType Action_Group_2_ELEMENT_TYPE = associate(ActionFactory.createAction_Group_2ElementType());

	public static final IGrammarAwareElementType Action_IntensityAssignment_2_0_ELEMENT_TYPE = associate(ActionFactory.createAction_IntensityAssignment_2_0ElementType());

	public static final IGrammarAwareElementType Action_IntensityIntensityEnumRuleCall_2_0_0_ELEMENT_TYPE = associate(ActionFactory.createAction_IntensityIntensityEnumRuleCall_2_0_0ElementType());

	public static final IGrammarAwareElementType Action_ActionHolderAssignment_2_1_ELEMENT_TYPE = associate(ActionFactory.createAction_ActionHolderAssignment_2_1ElementType());

	public static final IGrammarAwareElementType Action_ActionHolderDirectedActionParserRuleCall_2_1_0_ELEMENT_TYPE = associate(ActionFactory.createAction_ActionHolderDirectedActionParserRuleCall_2_1_0ElementType());

	private static class IntensityFactory {
		public static IGrammarAwareElementType createIntensityElementType() {
			return new IGrammarAwareElementType("Intensity_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getIntensityRule());
		}
		public static IGrammarAwareElementType createIntensity_AlternativesElementType() {
			return new IGrammarAwareElementType("Intensity_Alternatives_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getIntensityAccess().getAlternatives());
		}
		public static IGrammarAwareElementType createIntensity_CEnumLiteralDeclaration_0ElementType() {
			return new IGrammarAwareElementType("Intensity_CEnumLiteralDeclaration_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getIntensityAccess().getCEnumLiteralDeclaration_0());
		}
		public static IGrammarAwareElementType createIntensity_CPronouncedKeyword_0_0ElementType() {
			return new IGrammarAwareElementType("Intensity_CPronouncedKeyword_0_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getIntensityAccess().getCPronouncedKeyword_0_0());
		}
		public static IGrammarAwareElementType createIntensity_AEnumLiteralDeclaration_1ElementType() {
			return new IGrammarAwareElementType("Intensity_AEnumLiteralDeclaration_1_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getIntensityAccess().getAEnumLiteralDeclaration_1());
		}
		public static IGrammarAwareElementType createIntensity_ATraceOfKeyword_1_0ElementType() {
			return new IGrammarAwareElementType("Intensity_ATraceOfKeyword_1_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getIntensityAccess().getATraceOfKeyword_1_0());
		}
		public static IGrammarAwareElementType createIntensity_BEnumLiteralDeclaration_2ElementType() {
			return new IGrammarAwareElementType("Intensity_BEnumLiteralDeclaration_2_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getIntensityAccess().getBEnumLiteralDeclaration_2());
		}
		public static IGrammarAwareElementType createIntensity_BSlightlyKeyword_2_0ElementType() {
			return new IGrammarAwareElementType("Intensity_BSlightlyKeyword_2_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getIntensityAccess().getBSlightlyKeyword_2_0());
		}
		public static IGrammarAwareElementType createIntensity_DEnumLiteralDeclaration_3ElementType() {
			return new IGrammarAwareElementType("Intensity_DEnumLiteralDeclaration_3_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getIntensityAccess().getDEnumLiteralDeclaration_3());
		}
		public static IGrammarAwareElementType createIntensity_DSevereKeyword_3_0ElementType() {
			return new IGrammarAwareElementType("Intensity_DSevereKeyword_3_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getIntensityAccess().getDSevereKeyword_3_0());
		}
		public static IGrammarAwareElementType createIntensity_EEnumLiteralDeclaration_4ElementType() {
			return new IGrammarAwareElementType("Intensity_EEnumLiteralDeclaration_4_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getIntensityAccess().getEEnumLiteralDeclaration_4());
		}
		public static IGrammarAwareElementType createIntensity_EMaximumKeyword_4_0ElementType() {
			return new IGrammarAwareElementType("Intensity_EMaximumKeyword_4_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getIntensityAccess().getEMaximumKeyword_4_0());
		}
	}

	public static final IGrammarAwareElementType Intensity_ELEMENT_TYPE = associate(IntensityFactory.createIntensityElementType());

	public static final IGrammarAwareElementType Intensity_Alternatives_ELEMENT_TYPE = associate(IntensityFactory.createIntensity_AlternativesElementType());

	public static final IGrammarAwareElementType Intensity_CEnumLiteralDeclaration_0_ELEMENT_TYPE = associate(IntensityFactory.createIntensity_CEnumLiteralDeclaration_0ElementType());

	public static final IGrammarAwareElementType Intensity_CPronouncedKeyword_0_0_ELEMENT_TYPE = associate(IntensityFactory.createIntensity_CPronouncedKeyword_0_0ElementType());

	public static final IGrammarAwareElementType Intensity_AEnumLiteralDeclaration_1_ELEMENT_TYPE = associate(IntensityFactory.createIntensity_AEnumLiteralDeclaration_1ElementType());

	public static final IGrammarAwareElementType Intensity_ATraceOfKeyword_1_0_ELEMENT_TYPE = associate(IntensityFactory.createIntensity_ATraceOfKeyword_1_0ElementType());

	public static final IGrammarAwareElementType Intensity_BEnumLiteralDeclaration_2_ELEMENT_TYPE = associate(IntensityFactory.createIntensity_BEnumLiteralDeclaration_2ElementType());

	public static final IGrammarAwareElementType Intensity_BSlightlyKeyword_2_0_ELEMENT_TYPE = associate(IntensityFactory.createIntensity_BSlightlyKeyword_2_0ElementType());

	public static final IGrammarAwareElementType Intensity_DEnumLiteralDeclaration_3_ELEMENT_TYPE = associate(IntensityFactory.createIntensity_DEnumLiteralDeclaration_3ElementType());

	public static final IGrammarAwareElementType Intensity_DSevereKeyword_3_0_ELEMENT_TYPE = associate(IntensityFactory.createIntensity_DSevereKeyword_3_0ElementType());

	public static final IGrammarAwareElementType Intensity_EEnumLiteralDeclaration_4_ELEMENT_TYPE = associate(IntensityFactory.createIntensity_EEnumLiteralDeclaration_4ElementType());

	public static final IGrammarAwareElementType Intensity_EMaximumKeyword_4_0_ELEMENT_TYPE = associate(IntensityFactory.createIntensity_EMaximumKeyword_4_0ElementType());

	private static class CompleteActionFactory {
		public static IGrammarAwareElementType createCompleteActionElementType() {
			return new IGrammarAwareElementType("CompleteAction_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getCompleteActionRule());
		}
		public static IGrammarAwareElementType createCompleteAction_GroupElementType() {
			return new IGrammarAwareElementType("CompleteAction_Group_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getCompleteActionAccess().getGroup());
		}
		public static IGrammarAwareElementType createCompleteAction_ActionNameAssignment_0ElementType() {
			return new IGrammarAwareElementType("CompleteAction_ActionNameAssignment_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getCompleteActionAccess().getActionNameAssignment_0());
		}
		public static IGrammarAwareElementType createCompleteAction_ActionNameNeutralKeyword_0_0ElementType() {
			return new IGrammarAwareElementType("CompleteAction_ActionNameNeutralKeyword_0_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getCompleteActionAccess().getActionNameNeutralKeyword_0_0());
		}
		public static IGrammarAwareElementType createCompleteAction_FaceKeyword_1ElementType() {
			return new IGrammarAwareElementType("CompleteAction_FaceKeyword_1_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getCompleteActionAccess().getFaceKeyword_1());
		}
	}

	public static final IGrammarAwareElementType CompleteAction_ELEMENT_TYPE = associate(CompleteActionFactory.createCompleteActionElementType());

	public static final IGrammarAwareElementType CompleteAction_Group_ELEMENT_TYPE = associate(CompleteActionFactory.createCompleteAction_GroupElementType());

	public static final IGrammarAwareElementType CompleteAction_ActionNameAssignment_0_ELEMENT_TYPE = associate(CompleteActionFactory.createCompleteAction_ActionNameAssignment_0ElementType());

	public static final IGrammarAwareElementType CompleteAction_ActionNameNeutralKeyword_0_0_ELEMENT_TYPE = associate(CompleteActionFactory.createCompleteAction_ActionNameNeutralKeyword_0_0ElementType());

	public static final IGrammarAwareElementType CompleteAction_FaceKeyword_1_ELEMENT_TYPE = associate(CompleteActionFactory.createCompleteAction_FaceKeyword_1ElementType());

	private static class SingleActionFactory {
		public static IGrammarAwareElementType createSingleActionElementType() {
			return new IGrammarAwareElementType("SingleAction_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getSingleActionRule());
		}
		public static IGrammarAwareElementType createSingleAction_AlternativesElementType() {
			return new IGrammarAwareElementType("SingleAction_Alternatives_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getSingleActionAccess().getAlternatives());
		}
		public static IGrammarAwareElementType createSingleAction_ActionNameAssignment_0ElementType() {
			return new IGrammarAwareElementType("SingleAction_ActionNameAssignment_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getSingleActionAccess().getActionNameAssignment_0());
		}
		public static IGrammarAwareElementType createSingleAction_ActionNameDropJawKeyword_0_0ElementType() {
			return new IGrammarAwareElementType("SingleAction_ActionNameDropJawKeyword_0_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getSingleActionAccess().getActionNameDropJawKeyword_0_0());
		}
		public static IGrammarAwareElementType createSingleAction_ActionNameAssignment_1ElementType() {
			return new IGrammarAwareElementType("SingleAction_ActionNameAssignment_1_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getSingleActionAccess().getActionNameAssignment_1());
		}
		public static IGrammarAwareElementType createSingleAction_ActionNameNodHeadKeyword_1_0ElementType() {
			return new IGrammarAwareElementType("SingleAction_ActionNameNodHeadKeyword_1_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getSingleActionAccess().getActionNameNodHeadKeyword_1_0());
		}
	}

	public static final IGrammarAwareElementType SingleAction_ELEMENT_TYPE = associate(SingleActionFactory.createSingleActionElementType());

	public static final IGrammarAwareElementType SingleAction_Alternatives_ELEMENT_TYPE = associate(SingleActionFactory.createSingleAction_AlternativesElementType());

	public static final IGrammarAwareElementType SingleAction_ActionNameAssignment_0_ELEMENT_TYPE = associate(SingleActionFactory.createSingleAction_ActionNameAssignment_0ElementType());

	public static final IGrammarAwareElementType SingleAction_ActionNameDropJawKeyword_0_0_ELEMENT_TYPE = associate(SingleActionFactory.createSingleAction_ActionNameDropJawKeyword_0_0ElementType());

	public static final IGrammarAwareElementType SingleAction_ActionNameAssignment_1_ELEMENT_TYPE = associate(SingleActionFactory.createSingleAction_ActionNameAssignment_1ElementType());

	public static final IGrammarAwareElementType SingleAction_ActionNameNodHeadKeyword_1_0_ELEMENT_TYPE = associate(SingleActionFactory.createSingleAction_ActionNameNodHeadKeyword_1_0ElementType());

	private static class DirectedActionFactory {
		public static IGrammarAwareElementType createDirectedActionElementType() {
			return new IGrammarAwareElementType("DirectedAction_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDirectedActionRule());
		}
		public static IGrammarAwareElementType createDirectedAction_AlternativesElementType() {
			return new IGrammarAwareElementType("DirectedAction_Alternatives_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDirectedActionAccess().getAlternatives());
		}
		public static IGrammarAwareElementType createDirectedAction_Group_0ElementType() {
			return new IGrammarAwareElementType("DirectedAction_Group_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDirectedActionAccess().getGroup_0());
		}
		public static IGrammarAwareElementType createDirectedAction_ActionNameAssignment_0_0ElementType() {
			return new IGrammarAwareElementType("DirectedAction_ActionNameAssignment_0_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDirectedActionAccess().getActionNameAssignment_0_0());
		}
		public static IGrammarAwareElementType createDirectedAction_ActionNameLeftRightDirectedActionParserRuleCall_0_0_0ElementType() {
			return new IGrammarAwareElementType("DirectedAction_ActionNameLeftRightDirectedActionParserRuleCall_0_0_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDirectedActionAccess().getActionNameLeftRightDirectedActionParserRuleCall_0_0_0());
		}
		public static IGrammarAwareElementType createDirectedAction_DirectionAssignment_0_1ElementType() {
			return new IGrammarAwareElementType("DirectedAction_DirectionAssignment_0_1_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDirectedActionAccess().getDirectionAssignment_0_1());
		}
		public static IGrammarAwareElementType createDirectedAction_DirectionLeftRightDirectionParserRuleCall_0_1_0ElementType() {
			return new IGrammarAwareElementType("DirectedAction_DirectionLeftRightDirectionParserRuleCall_0_1_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDirectedActionAccess().getDirectionLeftRightDirectionParserRuleCall_0_1_0());
		}
		public static IGrammarAwareElementType createDirectedAction_Group_1ElementType() {
			return new IGrammarAwareElementType("DirectedAction_Group_1_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDirectedActionAccess().getGroup_1());
		}
		public static IGrammarAwareElementType createDirectedAction_ActionNameAssignment_1_0ElementType() {
			return new IGrammarAwareElementType("DirectedAction_ActionNameAssignment_1_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDirectedActionAccess().getActionNameAssignment_1_0());
		}
		public static IGrammarAwareElementType createDirectedAction_ActionNameBackForthDirectedActionParserRuleCall_1_0_0ElementType() {
			return new IGrammarAwareElementType("DirectedAction_ActionNameBackForthDirectedActionParserRuleCall_1_0_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDirectedActionAccess().getActionNameBackForthDirectedActionParserRuleCall_1_0_0());
		}
		public static IGrammarAwareElementType createDirectedAction_DirectionAssignment_1_1ElementType() {
			return new IGrammarAwareElementType("DirectedAction_DirectionAssignment_1_1_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDirectedActionAccess().getDirectionAssignment_1_1());
		}
		public static IGrammarAwareElementType createDirectedAction_DirectionBackForthDirectionParserRuleCall_1_1_0ElementType() {
			return new IGrammarAwareElementType("DirectedAction_DirectionBackForthDirectionParserRuleCall_1_1_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDirectedActionAccess().getDirectionBackForthDirectionParserRuleCall_1_1_0());
		}
		public static IGrammarAwareElementType createDirectedAction_Group_2ElementType() {
			return new IGrammarAwareElementType("DirectedAction_Group_2_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDirectedActionAccess().getGroup_2());
		}
		public static IGrammarAwareElementType createDirectedAction_ActionNameAssignment_2_0ElementType() {
			return new IGrammarAwareElementType("DirectedAction_ActionNameAssignment_2_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDirectedActionAccess().getActionNameAssignment_2_0());
		}
		public static IGrammarAwareElementType createDirectedAction_ActionNameFullDirectedActionParserRuleCall_2_0_0ElementType() {
			return new IGrammarAwareElementType("DirectedAction_ActionNameFullDirectedActionParserRuleCall_2_0_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDirectedActionAccess().getActionNameFullDirectedActionParserRuleCall_2_0_0());
		}
		public static IGrammarAwareElementType createDirectedAction_DirectionAssignment_2_1ElementType() {
			return new IGrammarAwareElementType("DirectedAction_DirectionAssignment_2_1_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDirectedActionAccess().getDirectionAssignment_2_1());
		}
		public static IGrammarAwareElementType createDirectedAction_DirectionDirectionParserRuleCall_2_1_0ElementType() {
			return new IGrammarAwareElementType("DirectedAction_DirectionDirectionParserRuleCall_2_1_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDirectedActionAccess().getDirectionDirectionParserRuleCall_2_1_0());
		}
	}

	public static final IGrammarAwareElementType DirectedAction_ELEMENT_TYPE = associate(DirectedActionFactory.createDirectedActionElementType());

	public static final IGrammarAwareElementType DirectedAction_Alternatives_ELEMENT_TYPE = associate(DirectedActionFactory.createDirectedAction_AlternativesElementType());

	public static final IGrammarAwareElementType DirectedAction_Group_0_ELEMENT_TYPE = associate(DirectedActionFactory.createDirectedAction_Group_0ElementType());

	public static final IGrammarAwareElementType DirectedAction_ActionNameAssignment_0_0_ELEMENT_TYPE = associate(DirectedActionFactory.createDirectedAction_ActionNameAssignment_0_0ElementType());

	public static final IGrammarAwareElementType DirectedAction_ActionNameLeftRightDirectedActionParserRuleCall_0_0_0_ELEMENT_TYPE = associate(DirectedActionFactory.createDirectedAction_ActionNameLeftRightDirectedActionParserRuleCall_0_0_0ElementType());

	public static final IGrammarAwareElementType DirectedAction_DirectionAssignment_0_1_ELEMENT_TYPE = associate(DirectedActionFactory.createDirectedAction_DirectionAssignment_0_1ElementType());

	public static final IGrammarAwareElementType DirectedAction_DirectionLeftRightDirectionParserRuleCall_0_1_0_ELEMENT_TYPE = associate(DirectedActionFactory.createDirectedAction_DirectionLeftRightDirectionParserRuleCall_0_1_0ElementType());

	public static final IGrammarAwareElementType DirectedAction_Group_1_ELEMENT_TYPE = associate(DirectedActionFactory.createDirectedAction_Group_1ElementType());

	public static final IGrammarAwareElementType DirectedAction_ActionNameAssignment_1_0_ELEMENT_TYPE = associate(DirectedActionFactory.createDirectedAction_ActionNameAssignment_1_0ElementType());

	public static final IGrammarAwareElementType DirectedAction_ActionNameBackForthDirectedActionParserRuleCall_1_0_0_ELEMENT_TYPE = associate(DirectedActionFactory.createDirectedAction_ActionNameBackForthDirectedActionParserRuleCall_1_0_0ElementType());

	public static final IGrammarAwareElementType DirectedAction_DirectionAssignment_1_1_ELEMENT_TYPE = associate(DirectedActionFactory.createDirectedAction_DirectionAssignment_1_1ElementType());

	public static final IGrammarAwareElementType DirectedAction_DirectionBackForthDirectionParserRuleCall_1_1_0_ELEMENT_TYPE = associate(DirectedActionFactory.createDirectedAction_DirectionBackForthDirectionParserRuleCall_1_1_0ElementType());

	public static final IGrammarAwareElementType DirectedAction_Group_2_ELEMENT_TYPE = associate(DirectedActionFactory.createDirectedAction_Group_2ElementType());

	public static final IGrammarAwareElementType DirectedAction_ActionNameAssignment_2_0_ELEMENT_TYPE = associate(DirectedActionFactory.createDirectedAction_ActionNameAssignment_2_0ElementType());

	public static final IGrammarAwareElementType DirectedAction_ActionNameFullDirectedActionParserRuleCall_2_0_0_ELEMENT_TYPE = associate(DirectedActionFactory.createDirectedAction_ActionNameFullDirectedActionParserRuleCall_2_0_0ElementType());

	public static final IGrammarAwareElementType DirectedAction_DirectionAssignment_2_1_ELEMENT_TYPE = associate(DirectedActionFactory.createDirectedAction_DirectionAssignment_2_1ElementType());

	public static final IGrammarAwareElementType DirectedAction_DirectionDirectionParserRuleCall_2_1_0_ELEMENT_TYPE = associate(DirectedActionFactory.createDirectedAction_DirectionDirectionParserRuleCall_2_1_0ElementType());

	private static class LeftRightDirectedActionFactory {
		public static IGrammarAwareElementType createLeftRightDirectedActionElementType() {
			return new IGrammarAwareElementType("LeftRightDirectedAction_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getLeftRightDirectedActionRule());
		}
		public static IGrammarAwareElementType createLeftRightDirectedAction_GroupElementType() {
			return new IGrammarAwareElementType("LeftRightDirectedAction_Group_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getLeftRightDirectedActionAccess().getGroup());
		}
		public static IGrammarAwareElementType createLeftRightDirectedAction_TiltHeadAssignment_0ElementType() {
			return new IGrammarAwareElementType("LeftRightDirectedAction_TiltHeadAssignment_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getLeftRightDirectedActionAccess().getTiltHeadAssignment_0());
		}
		public static IGrammarAwareElementType createLeftRightDirectedAction_TiltHeadTiltKeyword_0_0ElementType() {
			return new IGrammarAwareElementType("LeftRightDirectedAction_TiltHeadTiltKeyword_0_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getLeftRightDirectedActionAccess().getTiltHeadTiltKeyword_0_0());
		}
		public static IGrammarAwareElementType createLeftRightDirectedAction_HeadKeyword_1ElementType() {
			return new IGrammarAwareElementType("LeftRightDirectedAction_HeadKeyword_1_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getLeftRightDirectedActionAccess().getHeadKeyword_1());
		}
	}

	public static final IGrammarAwareElementType LeftRightDirectedAction_ELEMENT_TYPE = associate(LeftRightDirectedActionFactory.createLeftRightDirectedActionElementType());

	public static final IGrammarAwareElementType LeftRightDirectedAction_Group_ELEMENT_TYPE = associate(LeftRightDirectedActionFactory.createLeftRightDirectedAction_GroupElementType());

	public static final IGrammarAwareElementType LeftRightDirectedAction_TiltHeadAssignment_0_ELEMENT_TYPE = associate(LeftRightDirectedActionFactory.createLeftRightDirectedAction_TiltHeadAssignment_0ElementType());

	public static final IGrammarAwareElementType LeftRightDirectedAction_TiltHeadTiltKeyword_0_0_ELEMENT_TYPE = associate(LeftRightDirectedActionFactory.createLeftRightDirectedAction_TiltHeadTiltKeyword_0_0ElementType());

	public static final IGrammarAwareElementType LeftRightDirectedAction_HeadKeyword_1_ELEMENT_TYPE = associate(LeftRightDirectedActionFactory.createLeftRightDirectedAction_HeadKeyword_1ElementType());

	private static class LeftRightDirectionFactory {
		public static IGrammarAwareElementType createLeftRightDirectionElementType() {
			return new IGrammarAwareElementType("LeftRightDirection_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getLeftRightDirectionRule());
		}
		public static IGrammarAwareElementType createLeftRightDirection_AlternativesElementType() {
			return new IGrammarAwareElementType("LeftRightDirection_Alternatives_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getLeftRightDirectionAccess().getAlternatives());
		}
		public static IGrammarAwareElementType createLeftRightDirection_LeftAssignment_0ElementType() {
			return new IGrammarAwareElementType("LeftRightDirection_LeftAssignment_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getLeftRightDirectionAccess().getLeftAssignment_0());
		}
		public static IGrammarAwareElementType createLeftRightDirection_LeftLeftKeyword_0_0ElementType() {
			return new IGrammarAwareElementType("LeftRightDirection_LeftLeftKeyword_0_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getLeftRightDirectionAccess().getLeftLeftKeyword_0_0());
		}
		public static IGrammarAwareElementType createLeftRightDirection_RightAssignment_1ElementType() {
			return new IGrammarAwareElementType("LeftRightDirection_RightAssignment_1_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getLeftRightDirectionAccess().getRightAssignment_1());
		}
		public static IGrammarAwareElementType createLeftRightDirection_RightRightKeyword_1_0ElementType() {
			return new IGrammarAwareElementType("LeftRightDirection_RightRightKeyword_1_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getLeftRightDirectionAccess().getRightRightKeyword_1_0());
		}
	}

	public static final IGrammarAwareElementType LeftRightDirection_ELEMENT_TYPE = associate(LeftRightDirectionFactory.createLeftRightDirectionElementType());

	public static final IGrammarAwareElementType LeftRightDirection_Alternatives_ELEMENT_TYPE = associate(LeftRightDirectionFactory.createLeftRightDirection_AlternativesElementType());

	public static final IGrammarAwareElementType LeftRightDirection_LeftAssignment_0_ELEMENT_TYPE = associate(LeftRightDirectionFactory.createLeftRightDirection_LeftAssignment_0ElementType());

	public static final IGrammarAwareElementType LeftRightDirection_LeftLeftKeyword_0_0_ELEMENT_TYPE = associate(LeftRightDirectionFactory.createLeftRightDirection_LeftLeftKeyword_0_0ElementType());

	public static final IGrammarAwareElementType LeftRightDirection_RightAssignment_1_ELEMENT_TYPE = associate(LeftRightDirectionFactory.createLeftRightDirection_RightAssignment_1ElementType());

	public static final IGrammarAwareElementType LeftRightDirection_RightRightKeyword_1_0_ELEMENT_TYPE = associate(LeftRightDirectionFactory.createLeftRightDirection_RightRightKeyword_1_0ElementType());

	private static class BackForthDirectedActionFactory {
		public static IGrammarAwareElementType createBackForthDirectedActionElementType() {
			return new IGrammarAwareElementType("BackForthDirectedAction_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getBackForthDirectedActionRule());
		}
		public static IGrammarAwareElementType createBackForthDirectedAction_HeadAssignmentElementType() {
			return new IGrammarAwareElementType("BackForthDirectedAction_HeadAssignment_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getBackForthDirectedActionAccess().getHeadAssignment());
		}
		public static IGrammarAwareElementType createBackForthDirectedAction_HeadHeadKeyword_0ElementType() {
			return new IGrammarAwareElementType("BackForthDirectedAction_HeadHeadKeyword_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getBackForthDirectedActionAccess().getHeadHeadKeyword_0());
		}
	}

	public static final IGrammarAwareElementType BackForthDirectedAction_ELEMENT_TYPE = associate(BackForthDirectedActionFactory.createBackForthDirectedActionElementType());

	public static final IGrammarAwareElementType BackForthDirectedAction_HeadAssignment_ELEMENT_TYPE = associate(BackForthDirectedActionFactory.createBackForthDirectedAction_HeadAssignmentElementType());

	public static final IGrammarAwareElementType BackForthDirectedAction_HeadHeadKeyword_0_ELEMENT_TYPE = associate(BackForthDirectedActionFactory.createBackForthDirectedAction_HeadHeadKeyword_0ElementType());

	private static class BackForthDirectionFactory {
		public static IGrammarAwareElementType createBackForthDirectionElementType() {
			return new IGrammarAwareElementType("BackForthDirection_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getBackForthDirectionRule());
		}
		public static IGrammarAwareElementType createBackForthDirection_AlternativesElementType() {
			return new IGrammarAwareElementType("BackForthDirection_Alternatives_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getBackForthDirectionAccess().getAlternatives());
		}
		public static IGrammarAwareElementType createBackForthDirection_BackAssignment_0ElementType() {
			return new IGrammarAwareElementType("BackForthDirection_BackAssignment_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getBackForthDirectionAccess().getBackAssignment_0());
		}
		public static IGrammarAwareElementType createBackForthDirection_BackBackKeyword_0_0ElementType() {
			return new IGrammarAwareElementType("BackForthDirection_BackBackKeyword_0_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getBackForthDirectionAccess().getBackBackKeyword_0_0());
		}
		public static IGrammarAwareElementType createBackForthDirection_ForthAssignment_1ElementType() {
			return new IGrammarAwareElementType("BackForthDirection_ForthAssignment_1_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getBackForthDirectionAccess().getForthAssignment_1());
		}
		public static IGrammarAwareElementType createBackForthDirection_ForthForthKeyword_1_0ElementType() {
			return new IGrammarAwareElementType("BackForthDirection_ForthForthKeyword_1_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getBackForthDirectionAccess().getForthForthKeyword_1_0());
		}
	}

	public static final IGrammarAwareElementType BackForthDirection_ELEMENT_TYPE = associate(BackForthDirectionFactory.createBackForthDirectionElementType());

	public static final IGrammarAwareElementType BackForthDirection_Alternatives_ELEMENT_TYPE = associate(BackForthDirectionFactory.createBackForthDirection_AlternativesElementType());

	public static final IGrammarAwareElementType BackForthDirection_BackAssignment_0_ELEMENT_TYPE = associate(BackForthDirectionFactory.createBackForthDirection_BackAssignment_0ElementType());

	public static final IGrammarAwareElementType BackForthDirection_BackBackKeyword_0_0_ELEMENT_TYPE = associate(BackForthDirectionFactory.createBackForthDirection_BackBackKeyword_0_0ElementType());

	public static final IGrammarAwareElementType BackForthDirection_ForthAssignment_1_ELEMENT_TYPE = associate(BackForthDirectionFactory.createBackForthDirection_ForthAssignment_1ElementType());

	public static final IGrammarAwareElementType BackForthDirection_ForthForthKeyword_1_0_ELEMENT_TYPE = associate(BackForthDirectionFactory.createBackForthDirection_ForthForthKeyword_1_0ElementType());

	private static class FullDirectedActionFactory {
		public static IGrammarAwareElementType createFullDirectedActionElementType() {
			return new IGrammarAwareElementType("FullDirectedAction_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getFullDirectedActionRule());
		}
		public static IGrammarAwareElementType createFullDirectedAction_AlternativesElementType() {
			return new IGrammarAwareElementType("FullDirectedAction_Alternatives_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getFullDirectedActionAccess().getAlternatives());
		}
		public static IGrammarAwareElementType createFullDirectedAction_Group_0ElementType() {
			return new IGrammarAwareElementType("FullDirectedAction_Group_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getFullDirectedActionAccess().getGroup_0());
		}
		public static IGrammarAwareElementType createFullDirectedAction_TurnHeadAssignment_0_0ElementType() {
			return new IGrammarAwareElementType("FullDirectedAction_TurnHeadAssignment_0_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getFullDirectedActionAccess().getTurnHeadAssignment_0_0());
		}
		public static IGrammarAwareElementType createFullDirectedAction_TurnHeadTurnKeyword_0_0_0ElementType() {
			return new IGrammarAwareElementType("FullDirectedAction_TurnHeadTurnKeyword_0_0_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getFullDirectedActionAccess().getTurnHeadTurnKeyword_0_0_0());
		}
		public static IGrammarAwareElementType createFullDirectedAction_HeadKeyword_0_1ElementType() {
			return new IGrammarAwareElementType("FullDirectedAction_HeadKeyword_0_1_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getFullDirectedActionAccess().getHeadKeyword_0_1());
		}
		public static IGrammarAwareElementType createFullDirectedAction_Group_1ElementType() {
			return new IGrammarAwareElementType("FullDirectedAction_Group_1_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getFullDirectedActionAccess().getGroup_1());
		}
		public static IGrammarAwareElementType createFullDirectedAction_TurnEyesAssignment_1_0ElementType() {
			return new IGrammarAwareElementType("FullDirectedAction_TurnEyesAssignment_1_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getFullDirectedActionAccess().getTurnEyesAssignment_1_0());
		}
		public static IGrammarAwareElementType createFullDirectedAction_TurnEyesTurnKeyword_1_0_0ElementType() {
			return new IGrammarAwareElementType("FullDirectedAction_TurnEyesTurnKeyword_1_0_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getFullDirectedActionAccess().getTurnEyesTurnKeyword_1_0_0());
		}
		public static IGrammarAwareElementType createFullDirectedAction_EyesKeyword_1_1ElementType() {
			return new IGrammarAwareElementType("FullDirectedAction_EyesKeyword_1_1_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getFullDirectedActionAccess().getEyesKeyword_1_1());
		}
	}

	public static final IGrammarAwareElementType FullDirectedAction_ELEMENT_TYPE = associate(FullDirectedActionFactory.createFullDirectedActionElementType());

	public static final IGrammarAwareElementType FullDirectedAction_Alternatives_ELEMENT_TYPE = associate(FullDirectedActionFactory.createFullDirectedAction_AlternativesElementType());

	public static final IGrammarAwareElementType FullDirectedAction_Group_0_ELEMENT_TYPE = associate(FullDirectedActionFactory.createFullDirectedAction_Group_0ElementType());

	public static final IGrammarAwareElementType FullDirectedAction_TurnHeadAssignment_0_0_ELEMENT_TYPE = associate(FullDirectedActionFactory.createFullDirectedAction_TurnHeadAssignment_0_0ElementType());

	public static final IGrammarAwareElementType FullDirectedAction_TurnHeadTurnKeyword_0_0_0_ELEMENT_TYPE = associate(FullDirectedActionFactory.createFullDirectedAction_TurnHeadTurnKeyword_0_0_0ElementType());

	public static final IGrammarAwareElementType FullDirectedAction_HeadKeyword_0_1_ELEMENT_TYPE = associate(FullDirectedActionFactory.createFullDirectedAction_HeadKeyword_0_1ElementType());

	public static final IGrammarAwareElementType FullDirectedAction_Group_1_ELEMENT_TYPE = associate(FullDirectedActionFactory.createFullDirectedAction_Group_1ElementType());

	public static final IGrammarAwareElementType FullDirectedAction_TurnEyesAssignment_1_0_ELEMENT_TYPE = associate(FullDirectedActionFactory.createFullDirectedAction_TurnEyesAssignment_1_0ElementType());

	public static final IGrammarAwareElementType FullDirectedAction_TurnEyesTurnKeyword_1_0_0_ELEMENT_TYPE = associate(FullDirectedActionFactory.createFullDirectedAction_TurnEyesTurnKeyword_1_0_0ElementType());

	public static final IGrammarAwareElementType FullDirectedAction_EyesKeyword_1_1_ELEMENT_TYPE = associate(FullDirectedActionFactory.createFullDirectedAction_EyesKeyword_1_1ElementType());

	private static class DirectionFactory {
		public static IGrammarAwareElementType createDirectionElementType() {
			return new IGrammarAwareElementType("Direction_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDirectionRule());
		}
		public static IGrammarAwareElementType createDirection_AlternativesElementType() {
			return new IGrammarAwareElementType("Direction_Alternatives_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDirectionAccess().getAlternatives());
		}
		public static IGrammarAwareElementType createDirection_UPAssignment_0ElementType() {
			return new IGrammarAwareElementType("Direction_UPAssignment_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDirectionAccess().getUPAssignment_0());
		}
		public static IGrammarAwareElementType createDirection_UPUpKeyword_0_0ElementType() {
			return new IGrammarAwareElementType("Direction_UPUpKeyword_0_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDirectionAccess().getUPUpKeyword_0_0());
		}
		public static IGrammarAwareElementType createDirection_DOWNAssignment_1ElementType() {
			return new IGrammarAwareElementType("Direction_DOWNAssignment_1_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDirectionAccess().getDOWNAssignment_1());
		}
		public static IGrammarAwareElementType createDirection_DOWNDownKeyword_1_0ElementType() {
			return new IGrammarAwareElementType("Direction_DOWNDownKeyword_1_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDirectionAccess().getDOWNDownKeyword_1_0());
		}
		public static IGrammarAwareElementType createDirection_LEFTAssignment_2ElementType() {
			return new IGrammarAwareElementType("Direction_LEFTAssignment_2_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDirectionAccess().getLEFTAssignment_2());
		}
		public static IGrammarAwareElementType createDirection_LEFTLeftKeyword_2_0ElementType() {
			return new IGrammarAwareElementType("Direction_LEFTLeftKeyword_2_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDirectionAccess().getLEFTLeftKeyword_2_0());
		}
		public static IGrammarAwareElementType createDirection_RIGHTAssignment_3ElementType() {
			return new IGrammarAwareElementType("Direction_RIGHTAssignment_3_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDirectionAccess().getRIGHTAssignment_3());
		}
		public static IGrammarAwareElementType createDirection_RIGHTRightKeyword_3_0ElementType() {
			return new IGrammarAwareElementType("Direction_RIGHTRightKeyword_3_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDirectionAccess().getRIGHTRightKeyword_3_0());
		}
	}

	public static final IGrammarAwareElementType Direction_ELEMENT_TYPE = associate(DirectionFactory.createDirectionElementType());

	public static final IGrammarAwareElementType Direction_Alternatives_ELEMENT_TYPE = associate(DirectionFactory.createDirection_AlternativesElementType());

	public static final IGrammarAwareElementType Direction_UPAssignment_0_ELEMENT_TYPE = associate(DirectionFactory.createDirection_UPAssignment_0ElementType());

	public static final IGrammarAwareElementType Direction_UPUpKeyword_0_0_ELEMENT_TYPE = associate(DirectionFactory.createDirection_UPUpKeyword_0_0ElementType());

	public static final IGrammarAwareElementType Direction_DOWNAssignment_1_ELEMENT_TYPE = associate(DirectionFactory.createDirection_DOWNAssignment_1ElementType());

	public static final IGrammarAwareElementType Direction_DOWNDownKeyword_1_0_ELEMENT_TYPE = associate(DirectionFactory.createDirection_DOWNDownKeyword_1_0ElementType());

	public static final IGrammarAwareElementType Direction_LEFTAssignment_2_ELEMENT_TYPE = associate(DirectionFactory.createDirection_LEFTAssignment_2ElementType());

	public static final IGrammarAwareElementType Direction_LEFTLeftKeyword_2_0_ELEMENT_TYPE = associate(DirectionFactory.createDirection_LEFTLeftKeyword_2_0ElementType());

	public static final IGrammarAwareElementType Direction_RIGHTAssignment_3_ELEMENT_TYPE = associate(DirectionFactory.createDirection_RIGHTAssignment_3ElementType());

	public static final IGrammarAwareElementType Direction_RIGHTRightKeyword_3_0_ELEMENT_TYPE = associate(DirectionFactory.createDirection_RIGHTRightKeyword_3_0ElementType());

	private static class DurationUnitFactory {
		public static IGrammarAwareElementType createDurationUnitElementType() {
			return new IGrammarAwareElementType("DurationUnit_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDurationUnitRule());
		}
		public static IGrammarAwareElementType createDurationUnit_AlternativesElementType() {
			return new IGrammarAwareElementType("DurationUnit_Alternatives_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDurationUnitAccess().getAlternatives());
		}
		public static IGrammarAwareElementType createDurationUnit_MILLISECONDSEnumLiteralDeclaration_0ElementType() {
			return new IGrammarAwareElementType("DurationUnit_MILLISECONDSEnumLiteralDeclaration_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDurationUnitAccess().getMILLISECONDSEnumLiteralDeclaration_0());
		}
		public static IGrammarAwareElementType createDurationUnit_MILLISECONDSMillisecondsKeyword_0_0ElementType() {
			return new IGrammarAwareElementType("DurationUnit_MILLISECONDSMillisecondsKeyword_0_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDurationUnitAccess().getMILLISECONDSMillisecondsKeyword_0_0());
		}
		public static IGrammarAwareElementType createDurationUnit_SECONDSEnumLiteralDeclaration_1ElementType() {
			return new IGrammarAwareElementType("DurationUnit_SECONDSEnumLiteralDeclaration_1_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDurationUnitAccess().getSECONDSEnumLiteralDeclaration_1());
		}
		public static IGrammarAwareElementType createDurationUnit_SECONDSSecondsKeyword_1_0ElementType() {
			return new IGrammarAwareElementType("DurationUnit_SECONDSSecondsKeyword_1_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDurationUnitAccess().getSECONDSSecondsKeyword_1_0());
		}
		public static IGrammarAwareElementType createDurationUnit_MINUTESEnumLiteralDeclaration_2ElementType() {
			return new IGrammarAwareElementType("DurationUnit_MINUTESEnumLiteralDeclaration_2_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDurationUnitAccess().getMINUTESEnumLiteralDeclaration_2());
		}
		public static IGrammarAwareElementType createDurationUnit_MINUTESMinutesKeyword_2_0ElementType() {
			return new IGrammarAwareElementType("DurationUnit_MINUTESMinutesKeyword_2_0_ELEMENT_TYPE", RocLanguage.INSTANCE, GRAMMAR_ACCESS.getDurationUnitAccess().getMINUTESMinutesKeyword_2_0());
		}
	}

	public static final IGrammarAwareElementType DurationUnit_ELEMENT_TYPE = associate(DurationUnitFactory.createDurationUnitElementType());

	public static final IGrammarAwareElementType DurationUnit_Alternatives_ELEMENT_TYPE = associate(DurationUnitFactory.createDurationUnit_AlternativesElementType());

	public static final IGrammarAwareElementType DurationUnit_MILLISECONDSEnumLiteralDeclaration_0_ELEMENT_TYPE = associate(DurationUnitFactory.createDurationUnit_MILLISECONDSEnumLiteralDeclaration_0ElementType());

	public static final IGrammarAwareElementType DurationUnit_MILLISECONDSMillisecondsKeyword_0_0_ELEMENT_TYPE = associate(DurationUnitFactory.createDurationUnit_MILLISECONDSMillisecondsKeyword_0_0ElementType());

	public static final IGrammarAwareElementType DurationUnit_SECONDSEnumLiteralDeclaration_1_ELEMENT_TYPE = associate(DurationUnitFactory.createDurationUnit_SECONDSEnumLiteralDeclaration_1ElementType());

	public static final IGrammarAwareElementType DurationUnit_SECONDSSecondsKeyword_1_0_ELEMENT_TYPE = associate(DurationUnitFactory.createDurationUnit_SECONDSSecondsKeyword_1_0ElementType());

	public static final IGrammarAwareElementType DurationUnit_MINUTESEnumLiteralDeclaration_2_ELEMENT_TYPE = associate(DurationUnitFactory.createDurationUnit_MINUTESEnumLiteralDeclaration_2ElementType());

	public static final IGrammarAwareElementType DurationUnit_MINUTESMinutesKeyword_2_0_ELEMENT_TYPE = associate(DurationUnitFactory.createDurationUnit_MINUTESMinutesKeyword_2_0ElementType());

	@Override
	public IFileElementType getFileType() {
		return FILE_TYPE;
	}

	@Override
	public IGrammarAwareElementType findElementType(EObject grammarElement) {
		return GRAMMAR_ELEMENT_TYPE.get(grammarElement);
	}
	
	public IGrammarAwareElementType getProgramElementType() {
		return Program_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getProgram_MovementsAssignmentElementType() {
		return Program_MovementsAssignment_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getProgram_MovementsMovementParserRuleCall_0ElementType() {
		return Program_MovementsMovementParserRuleCall_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getMovementElementType() {
		return Movement_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getMovement_GroupElementType() {
		return Movement_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getMovement_MotionsAssignment_0ElementType() {
		return Movement_MotionsAssignment_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getMovement_MotionsMotionParserRuleCall_0_0ElementType() {
		return Movement_MotionsMotionParserRuleCall_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getMovement_Group_1ElementType() {
		return Movement_Group_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getMovement_ANDTerminalRuleCall_1_0ElementType() {
		return Movement_ANDTerminalRuleCall_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getMovement_MotionsAssignment_1_1ElementType() {
		return Movement_MotionsAssignment_1_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getMovement_MotionsMotionParserRuleCall_1_1_0ElementType() {
		return Movement_MotionsMotionParserRuleCall_1_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getMovement_PERIODTerminalRuleCall_2ElementType() {
		return Movement_PERIODTerminalRuleCall_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getMotionElementType() {
		return Motion_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getMotion_GroupElementType() {
		return Motion_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getMotion_ActionAssignment_0ElementType() {
		return Motion_ActionAssignment_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getMotion_ActionActionParserRuleCall_0_0ElementType() {
		return Motion_ActionActionParserRuleCall_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getMotion_FORTerminalRuleCall_1ElementType() {
		return Motion_FORTerminalRuleCall_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getMotion_DurationAssignment_2ElementType() {
		return Motion_DurationAssignment_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getMotion_DurationDurationTerminalRuleCall_2_0ElementType() {
		return Motion_DurationDurationTerminalRuleCall_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getMotion_DurationUnitAssignment_3ElementType() {
		return Motion_DurationUnitAssignment_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getMotion_DurationUnitDurationUnitEnumRuleCall_3_0ElementType() {
		return Motion_DurationUnitDurationUnitEnumRuleCall_3_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getActionElementType() {
		return Action_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAction_AlternativesElementType() {
		return Action_Alternatives_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAction_ActionHolderAssignment_0ElementType() {
		return Action_ActionHolderAssignment_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAction_ActionHolderCompleteActionParserRuleCall_0_0ElementType() {
		return Action_ActionHolderCompleteActionParserRuleCall_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAction_Group_1ElementType() {
		return Action_Group_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAction_IntensityAssignment_1_0ElementType() {
		return Action_IntensityAssignment_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAction_IntensityIntensityEnumRuleCall_1_0_0ElementType() {
		return Action_IntensityIntensityEnumRuleCall_1_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAction_ActionHolderAssignment_1_1ElementType() {
		return Action_ActionHolderAssignment_1_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAction_ActionHolderSingleActionParserRuleCall_1_1_0ElementType() {
		return Action_ActionHolderSingleActionParserRuleCall_1_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAction_Group_2ElementType() {
		return Action_Group_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAction_IntensityAssignment_2_0ElementType() {
		return Action_IntensityAssignment_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAction_IntensityIntensityEnumRuleCall_2_0_0ElementType() {
		return Action_IntensityIntensityEnumRuleCall_2_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAction_ActionHolderAssignment_2_1ElementType() {
		return Action_ActionHolderAssignment_2_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAction_ActionHolderDirectedActionParserRuleCall_2_1_0ElementType() {
		return Action_ActionHolderDirectedActionParserRuleCall_2_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getIntensityElementType() {
		return Intensity_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getIntensity_AlternativesElementType() {
		return Intensity_Alternatives_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getIntensity_CEnumLiteralDeclaration_0ElementType() {
		return Intensity_CEnumLiteralDeclaration_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getIntensity_CPronouncedKeyword_0_0ElementType() {
		return Intensity_CPronouncedKeyword_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getIntensity_AEnumLiteralDeclaration_1ElementType() {
		return Intensity_AEnumLiteralDeclaration_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getIntensity_ATraceOfKeyword_1_0ElementType() {
		return Intensity_ATraceOfKeyword_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getIntensity_BEnumLiteralDeclaration_2ElementType() {
		return Intensity_BEnumLiteralDeclaration_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getIntensity_BSlightlyKeyword_2_0ElementType() {
		return Intensity_BSlightlyKeyword_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getIntensity_DEnumLiteralDeclaration_3ElementType() {
		return Intensity_DEnumLiteralDeclaration_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getIntensity_DSevereKeyword_3_0ElementType() {
		return Intensity_DSevereKeyword_3_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getIntensity_EEnumLiteralDeclaration_4ElementType() {
		return Intensity_EEnumLiteralDeclaration_4_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getIntensity_EMaximumKeyword_4_0ElementType() {
		return Intensity_EMaximumKeyword_4_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getCompleteActionElementType() {
		return CompleteAction_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getCompleteAction_GroupElementType() {
		return CompleteAction_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getCompleteAction_ActionNameAssignment_0ElementType() {
		return CompleteAction_ActionNameAssignment_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getCompleteAction_ActionNameNeutralKeyword_0_0ElementType() {
		return CompleteAction_ActionNameNeutralKeyword_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getCompleteAction_FaceKeyword_1ElementType() {
		return CompleteAction_FaceKeyword_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSingleActionElementType() {
		return SingleAction_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSingleAction_AlternativesElementType() {
		return SingleAction_Alternatives_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSingleAction_ActionNameAssignment_0ElementType() {
		return SingleAction_ActionNameAssignment_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSingleAction_ActionNameDropJawKeyword_0_0ElementType() {
		return SingleAction_ActionNameDropJawKeyword_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSingleAction_ActionNameAssignment_1ElementType() {
		return SingleAction_ActionNameAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSingleAction_ActionNameNodHeadKeyword_1_0ElementType() {
		return SingleAction_ActionNameNodHeadKeyword_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDirectedActionElementType() {
		return DirectedAction_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDirectedAction_AlternativesElementType() {
		return DirectedAction_Alternatives_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDirectedAction_Group_0ElementType() {
		return DirectedAction_Group_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDirectedAction_ActionNameAssignment_0_0ElementType() {
		return DirectedAction_ActionNameAssignment_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDirectedAction_ActionNameLeftRightDirectedActionParserRuleCall_0_0_0ElementType() {
		return DirectedAction_ActionNameLeftRightDirectedActionParserRuleCall_0_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDirectedAction_DirectionAssignment_0_1ElementType() {
		return DirectedAction_DirectionAssignment_0_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDirectedAction_DirectionLeftRightDirectionParserRuleCall_0_1_0ElementType() {
		return DirectedAction_DirectionLeftRightDirectionParserRuleCall_0_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDirectedAction_Group_1ElementType() {
		return DirectedAction_Group_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDirectedAction_ActionNameAssignment_1_0ElementType() {
		return DirectedAction_ActionNameAssignment_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDirectedAction_ActionNameBackForthDirectedActionParserRuleCall_1_0_0ElementType() {
		return DirectedAction_ActionNameBackForthDirectedActionParserRuleCall_1_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDirectedAction_DirectionAssignment_1_1ElementType() {
		return DirectedAction_DirectionAssignment_1_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDirectedAction_DirectionBackForthDirectionParserRuleCall_1_1_0ElementType() {
		return DirectedAction_DirectionBackForthDirectionParserRuleCall_1_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDirectedAction_Group_2ElementType() {
		return DirectedAction_Group_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDirectedAction_ActionNameAssignment_2_0ElementType() {
		return DirectedAction_ActionNameAssignment_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDirectedAction_ActionNameFullDirectedActionParserRuleCall_2_0_0ElementType() {
		return DirectedAction_ActionNameFullDirectedActionParserRuleCall_2_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDirectedAction_DirectionAssignment_2_1ElementType() {
		return DirectedAction_DirectionAssignment_2_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDirectedAction_DirectionDirectionParserRuleCall_2_1_0ElementType() {
		return DirectedAction_DirectionDirectionParserRuleCall_2_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getLeftRightDirectedActionElementType() {
		return LeftRightDirectedAction_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getLeftRightDirectedAction_GroupElementType() {
		return LeftRightDirectedAction_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getLeftRightDirectedAction_TiltHeadAssignment_0ElementType() {
		return LeftRightDirectedAction_TiltHeadAssignment_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getLeftRightDirectedAction_TiltHeadTiltKeyword_0_0ElementType() {
		return LeftRightDirectedAction_TiltHeadTiltKeyword_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getLeftRightDirectedAction_HeadKeyword_1ElementType() {
		return LeftRightDirectedAction_HeadKeyword_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getLeftRightDirectionElementType() {
		return LeftRightDirection_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getLeftRightDirection_AlternativesElementType() {
		return LeftRightDirection_Alternatives_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getLeftRightDirection_LeftAssignment_0ElementType() {
		return LeftRightDirection_LeftAssignment_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getLeftRightDirection_LeftLeftKeyword_0_0ElementType() {
		return LeftRightDirection_LeftLeftKeyword_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getLeftRightDirection_RightAssignment_1ElementType() {
		return LeftRightDirection_RightAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getLeftRightDirection_RightRightKeyword_1_0ElementType() {
		return LeftRightDirection_RightRightKeyword_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getBackForthDirectedActionElementType() {
		return BackForthDirectedAction_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getBackForthDirectedAction_HeadAssignmentElementType() {
		return BackForthDirectedAction_HeadAssignment_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getBackForthDirectedAction_HeadHeadKeyword_0ElementType() {
		return BackForthDirectedAction_HeadHeadKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getBackForthDirectionElementType() {
		return BackForthDirection_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getBackForthDirection_AlternativesElementType() {
		return BackForthDirection_Alternatives_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getBackForthDirection_BackAssignment_0ElementType() {
		return BackForthDirection_BackAssignment_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getBackForthDirection_BackBackKeyword_0_0ElementType() {
		return BackForthDirection_BackBackKeyword_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getBackForthDirection_ForthAssignment_1ElementType() {
		return BackForthDirection_ForthAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getBackForthDirection_ForthForthKeyword_1_0ElementType() {
		return BackForthDirection_ForthForthKeyword_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFullDirectedActionElementType() {
		return FullDirectedAction_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFullDirectedAction_AlternativesElementType() {
		return FullDirectedAction_Alternatives_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFullDirectedAction_Group_0ElementType() {
		return FullDirectedAction_Group_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFullDirectedAction_TurnHeadAssignment_0_0ElementType() {
		return FullDirectedAction_TurnHeadAssignment_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFullDirectedAction_TurnHeadTurnKeyword_0_0_0ElementType() {
		return FullDirectedAction_TurnHeadTurnKeyword_0_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFullDirectedAction_HeadKeyword_0_1ElementType() {
		return FullDirectedAction_HeadKeyword_0_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFullDirectedAction_Group_1ElementType() {
		return FullDirectedAction_Group_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFullDirectedAction_TurnEyesAssignment_1_0ElementType() {
		return FullDirectedAction_TurnEyesAssignment_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFullDirectedAction_TurnEyesTurnKeyword_1_0_0ElementType() {
		return FullDirectedAction_TurnEyesTurnKeyword_1_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getFullDirectedAction_EyesKeyword_1_1ElementType() {
		return FullDirectedAction_EyesKeyword_1_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDirectionElementType() {
		return Direction_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDirection_AlternativesElementType() {
		return Direction_Alternatives_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDirection_UPAssignment_0ElementType() {
		return Direction_UPAssignment_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDirection_UPUpKeyword_0_0ElementType() {
		return Direction_UPUpKeyword_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDirection_DOWNAssignment_1ElementType() {
		return Direction_DOWNAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDirection_DOWNDownKeyword_1_0ElementType() {
		return Direction_DOWNDownKeyword_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDirection_LEFTAssignment_2ElementType() {
		return Direction_LEFTAssignment_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDirection_LEFTLeftKeyword_2_0ElementType() {
		return Direction_LEFTLeftKeyword_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDirection_RIGHTAssignment_3ElementType() {
		return Direction_RIGHTAssignment_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDirection_RIGHTRightKeyword_3_0ElementType() {
		return Direction_RIGHTRightKeyword_3_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDurationUnitElementType() {
		return DurationUnit_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDurationUnit_AlternativesElementType() {
		return DurationUnit_Alternatives_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDurationUnit_MILLISECONDSEnumLiteralDeclaration_0ElementType() {
		return DurationUnit_MILLISECONDSEnumLiteralDeclaration_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDurationUnit_MILLISECONDSMillisecondsKeyword_0_0ElementType() {
		return DurationUnit_MILLISECONDSMillisecondsKeyword_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDurationUnit_SECONDSEnumLiteralDeclaration_1ElementType() {
		return DurationUnit_SECONDSEnumLiteralDeclaration_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDurationUnit_SECONDSSecondsKeyword_1_0ElementType() {
		return DurationUnit_SECONDSSecondsKeyword_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDurationUnit_MINUTESEnumLiteralDeclaration_2ElementType() {
		return DurationUnit_MINUTESEnumLiteralDeclaration_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getDurationUnit_MINUTESMinutesKeyword_2_0ElementType() {
		return DurationUnit_MINUTESMinutesKeyword_2_0_ELEMENT_TYPE;
	}

}
