/**
 * generated by Xtext 2.10.0
 */
package robot.control.idea.lang;

import robot.control.idea.lang.AbstractRocFileType;

@SuppressWarnings("all")
public class RocFileType extends AbstractRocFileType {
  public final static RocFileType INSTANCE = new RocFileType();
  
  public RocFileType() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(RocLanguage) is undefined");
  }
}
