/*
 * generated by Xtext 2.10.0
 */
package robot.control.idea.completion;

import org.eclipse.xtext.common.idea.completion.TerminalsCompletionContributor;
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public class AbstractRocCompletionContributor extends TerminalsCompletionContributor {
	public AbstractRocCompletionContributor(AbstractXtextLanguage lang) {
		super(lang);
	}
}
