/**
 * generated by Xtext 2.10.0
 */
package robot.control.roc.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import robot.control.roc.Action;
import robot.control.roc.BackForthDirectedAction;
import robot.control.roc.BackForthDirection;
import robot.control.roc.CompleteAction;
import robot.control.roc.DirectedAction;
import robot.control.roc.Direction;
import robot.control.roc.DurationUnit;
import robot.control.roc.FullDirectedAction;
import robot.control.roc.Intensity;
import robot.control.roc.LeftRightDirectedAction;
import robot.control.roc.LeftRightDirection;
import robot.control.roc.Motion;
import robot.control.roc.Movement;
import robot.control.roc.Program;
import robot.control.roc.RocFactory;
import robot.control.roc.RocPackage;
import robot.control.roc.SingleAction;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class RocPackageImpl extends EPackageImpl implements RocPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass programEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass movementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass motionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass actionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass completeActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass singleActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass directedActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass leftRightDirectedActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass leftRightDirectionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass backForthDirectedActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass backForthDirectionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass fullDirectedActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass directionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum intensityEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum durationUnitEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see robot.control.roc.RocPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private RocPackageImpl()
  {
    super(eNS_URI, RocFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   * 
   * <p>This method is used to initialize {@link RocPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static RocPackage init()
  {
    if (isInited) return (RocPackage)EPackage.Registry.INSTANCE.getEPackage(RocPackage.eNS_URI);

    // Obtain or create and register package
    RocPackageImpl theRocPackage = (RocPackageImpl)(EPackage.Registry.INSTANCE.get(eNS_URI) instanceof RocPackageImpl ? EPackage.Registry.INSTANCE.get(eNS_URI) : new RocPackageImpl());

    isInited = true;

    // Create package meta-data objects
    theRocPackage.createPackageContents();

    // Initialize created meta-data
    theRocPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theRocPackage.freeze();

  
    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(RocPackage.eNS_URI, theRocPackage);
    return theRocPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getProgram()
  {
    return programEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getProgram_Movements()
  {
    return (EReference)programEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMovement()
  {
    return movementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getMovement_Motions()
  {
    return (EReference)movementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMotion()
  {
    return motionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getMotion_Action()
  {
    return (EReference)motionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMotion_Duration()
  {
    return (EAttribute)motionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMotion_DurationUnit()
  {
    return (EAttribute)motionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAction()
  {
    return actionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAction_ActionHolder()
  {
    return (EReference)actionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getAction_Intensity()
  {
    return (EAttribute)actionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCompleteAction()
  {
    return completeActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getCompleteAction_ActionName()
  {
    return (EAttribute)completeActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSingleAction()
  {
    return singleActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getSingleAction_ActionName()
  {
    return (EAttribute)singleActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDirectedAction()
  {
    return directedActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDirectedAction_ActionName()
  {
    return (EReference)directedActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDirectedAction_Direction()
  {
    return (EReference)directedActionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getLeftRightDirectedAction()
  {
    return leftRightDirectedActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getLeftRightDirectedAction_TiltHead()
  {
    return (EAttribute)leftRightDirectedActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getLeftRightDirection()
  {
    return leftRightDirectionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getLeftRightDirection_Left()
  {
    return (EAttribute)leftRightDirectionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getLeftRightDirection_Right()
  {
    return (EAttribute)leftRightDirectionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getBackForthDirectedAction()
  {
    return backForthDirectedActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getBackForthDirectedAction_Head()
  {
    return (EAttribute)backForthDirectedActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getBackForthDirection()
  {
    return backForthDirectionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getBackForthDirection_Back()
  {
    return (EAttribute)backForthDirectionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getBackForthDirection_Forth()
  {
    return (EAttribute)backForthDirectionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getFullDirectedAction()
  {
    return fullDirectedActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getFullDirectedAction_TurnHead()
  {
    return (EAttribute)fullDirectedActionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getFullDirectedAction_TurnEyes()
  {
    return (EAttribute)fullDirectedActionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDirection()
  {
    return directionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDirection_UP()
  {
    return (EAttribute)directionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDirection_DOWN()
  {
    return (EAttribute)directionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDirection_LEFT()
  {
    return (EAttribute)directionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDirection_RIGHT()
  {
    return (EAttribute)directionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getIntensity()
  {
    return intensityEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getDurationUnit()
  {
    return durationUnitEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RocFactory getRocFactory()
  {
    return (RocFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    programEClass = createEClass(PROGRAM);
    createEReference(programEClass, PROGRAM__MOVEMENTS);

    movementEClass = createEClass(MOVEMENT);
    createEReference(movementEClass, MOVEMENT__MOTIONS);

    motionEClass = createEClass(MOTION);
    createEReference(motionEClass, MOTION__ACTION);
    createEAttribute(motionEClass, MOTION__DURATION);
    createEAttribute(motionEClass, MOTION__DURATION_UNIT);

    actionEClass = createEClass(ACTION);
    createEReference(actionEClass, ACTION__ACTION_HOLDER);
    createEAttribute(actionEClass, ACTION__INTENSITY);

    completeActionEClass = createEClass(COMPLETE_ACTION);
    createEAttribute(completeActionEClass, COMPLETE_ACTION__ACTION_NAME);

    singleActionEClass = createEClass(SINGLE_ACTION);
    createEAttribute(singleActionEClass, SINGLE_ACTION__ACTION_NAME);

    directedActionEClass = createEClass(DIRECTED_ACTION);
    createEReference(directedActionEClass, DIRECTED_ACTION__ACTION_NAME);
    createEReference(directedActionEClass, DIRECTED_ACTION__DIRECTION);

    leftRightDirectedActionEClass = createEClass(LEFT_RIGHT_DIRECTED_ACTION);
    createEAttribute(leftRightDirectedActionEClass, LEFT_RIGHT_DIRECTED_ACTION__TILT_HEAD);

    leftRightDirectionEClass = createEClass(LEFT_RIGHT_DIRECTION);
    createEAttribute(leftRightDirectionEClass, LEFT_RIGHT_DIRECTION__LEFT);
    createEAttribute(leftRightDirectionEClass, LEFT_RIGHT_DIRECTION__RIGHT);

    backForthDirectedActionEClass = createEClass(BACK_FORTH_DIRECTED_ACTION);
    createEAttribute(backForthDirectedActionEClass, BACK_FORTH_DIRECTED_ACTION__HEAD);

    backForthDirectionEClass = createEClass(BACK_FORTH_DIRECTION);
    createEAttribute(backForthDirectionEClass, BACK_FORTH_DIRECTION__BACK);
    createEAttribute(backForthDirectionEClass, BACK_FORTH_DIRECTION__FORTH);

    fullDirectedActionEClass = createEClass(FULL_DIRECTED_ACTION);
    createEAttribute(fullDirectedActionEClass, FULL_DIRECTED_ACTION__TURN_HEAD);
    createEAttribute(fullDirectedActionEClass, FULL_DIRECTED_ACTION__TURN_EYES);

    directionEClass = createEClass(DIRECTION);
    createEAttribute(directionEClass, DIRECTION__UP);
    createEAttribute(directionEClass, DIRECTION__DOWN);
    createEAttribute(directionEClass, DIRECTION__LEFT);
    createEAttribute(directionEClass, DIRECTION__RIGHT);

    // Create enums
    intensityEEnum = createEEnum(INTENSITY);
    durationUnitEEnum = createEEnum(DURATION_UNIT);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes

    // Initialize classes and features; add operations and parameters
    initEClass(programEClass, Program.class, "Program", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getProgram_Movements(), this.getMovement(), null, "movements", null, 0, -1, Program.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(movementEClass, Movement.class, "Movement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getMovement_Motions(), this.getMotion(), null, "motions", null, 0, -1, Movement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(motionEClass, Motion.class, "Motion", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getMotion_Action(), this.getAction(), null, "action", null, 0, 1, Motion.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMotion_Duration(), ecorePackage.getEString(), "duration", null, 0, 1, Motion.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMotion_DurationUnit(), this.getDurationUnit(), "durationUnit", null, 0, 1, Motion.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(actionEClass, Action.class, "Action", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getAction_ActionHolder(), ecorePackage.getEObject(), null, "actionHolder", null, 0, 1, Action.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAction_Intensity(), this.getIntensity(), "intensity", null, 0, 1, Action.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(completeActionEClass, CompleteAction.class, "CompleteAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCompleteAction_ActionName(), ecorePackage.getEString(), "actionName", null, 0, 1, CompleteAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(singleActionEClass, SingleAction.class, "SingleAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSingleAction_ActionName(), ecorePackage.getEString(), "actionName", null, 0, 1, SingleAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(directedActionEClass, DirectedAction.class, "DirectedAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDirectedAction_ActionName(), ecorePackage.getEObject(), null, "actionName", null, 0, 1, DirectedAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDirectedAction_Direction(), ecorePackage.getEObject(), null, "direction", null, 0, 1, DirectedAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(leftRightDirectedActionEClass, LeftRightDirectedAction.class, "LeftRightDirectedAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLeftRightDirectedAction_TiltHead(), ecorePackage.getEString(), "tiltHead", null, 0, 1, LeftRightDirectedAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(leftRightDirectionEClass, LeftRightDirection.class, "LeftRightDirection", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLeftRightDirection_Left(), ecorePackage.getEString(), "left", null, 0, 1, LeftRightDirection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getLeftRightDirection_Right(), ecorePackage.getEString(), "right", null, 0, 1, LeftRightDirection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(backForthDirectedActionEClass, BackForthDirectedAction.class, "BackForthDirectedAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getBackForthDirectedAction_Head(), ecorePackage.getEString(), "head", null, 0, 1, BackForthDirectedAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(backForthDirectionEClass, BackForthDirection.class, "BackForthDirection", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getBackForthDirection_Back(), ecorePackage.getEString(), "back", null, 0, 1, BackForthDirection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getBackForthDirection_Forth(), ecorePackage.getEString(), "forth", null, 0, 1, BackForthDirection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(fullDirectedActionEClass, FullDirectedAction.class, "FullDirectedAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFullDirectedAction_TurnHead(), ecorePackage.getEString(), "turnHead", null, 0, 1, FullDirectedAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getFullDirectedAction_TurnEyes(), ecorePackage.getEString(), "turnEyes", null, 0, 1, FullDirectedAction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(directionEClass, Direction.class, "Direction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDirection_UP(), ecorePackage.getEString(), "UP", null, 0, 1, Direction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDirection_DOWN(), ecorePackage.getEString(), "DOWN", null, 0, 1, Direction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDirection_LEFT(), ecorePackage.getEString(), "LEFT", null, 0, 1, Direction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDirection_RIGHT(), ecorePackage.getEString(), "RIGHT", null, 0, 1, Direction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(intensityEEnum, Intensity.class, "Intensity");
    addEEnumLiteral(intensityEEnum, Intensity.C);
    addEEnumLiteral(intensityEEnum, Intensity.A);
    addEEnumLiteral(intensityEEnum, Intensity.B);
    addEEnumLiteral(intensityEEnum, Intensity.D);
    addEEnumLiteral(intensityEEnum, Intensity.E);

    initEEnum(durationUnitEEnum, DurationUnit.class, "DurationUnit");
    addEEnumLiteral(durationUnitEEnum, DurationUnit.MILLISECONDS);
    addEEnumLiteral(durationUnitEEnum, DurationUnit.SECONDS);
    addEEnumLiteral(durationUnitEEnum, DurationUnit.MINUTES);

    // Create resource
    createResource(eNS_URI);
  }

} //RocPackageImpl
