/*
 * generated by Xtext 2.10.0
 */
package robot.control.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class RocIdeaModule extends AbstractRocIdeaModule {
}
