set(_CATKIN_CURRENT_PACKAGE "roc")
set(roc_VERSION "0.1.0")
set(roc_MAINTAINER "iliadobrusin <iliadobrusin@freenet.de>")
set(roc_PACKAGE_FORMAT "1")
set(roc_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation")
set(roc_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation" "message_runtime")
set(roc_BUILDTOOL_DEPENDS "catkin")
set(roc_BUILDTOOL_EXPORT_DEPENDS )
set(roc_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation" "message_runtime")
set(roc_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation" "message_runtime")
set(roc_TEST_DEPENDS )
set(roc_DOC_DEPENDS )
set(roc_DEPRECATED "")