/**
 * generated by Xtext 2.10.0
 */
package robotcontrol.ui.contentassist;

import robotcontrol.ui.contentassist.AbstractRocProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class RocProposalProvider extends AbstractRocProposalProvider {
}
