/*
 * generated by Xtext 2.10.0
 */
package robotcontrol


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RocStandaloneSetup extends RocStandaloneSetupGenerated {

	def static void doSetup() {
		new RocStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
