/*
 * generated by Xtext 2.10.0
 */
package robotcontrol.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import robotcontrol.ui.internal.RobotcontrolActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RocExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RobotcontrolActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RobotcontrolActivator.getInstance().getInjector(RobotcontrolActivator.ROBOTCONTROL_ROC);
	}
	
}
