/**
 * generated by Xtext 2.10.0
 */
package robotcontrol.validation;

import robotcontrol.validation.AbstractRocValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class RocValidator extends AbstractRocValidator {
}
