/*
 * generated by Xtext 2.10.0
 */
package robot.control.idea.lang.psi;

import com.intellij.psi.util.PsiModificationTracker;
import org.eclipse.xtext.psi.BaseXtextCodeBlockModificationListener;
import robot.control.idea.lang.RocLanguage;

public class RocCodeBlockModificationListener extends BaseXtextCodeBlockModificationListener {

	public RocCodeBlockModificationListener(PsiModificationTracker psiModificationTracker) {
		super(RocLanguage.INSTANCE, psiModificationTracker);
	}

}
