/*
 * generated by Xtext 2.10.0
 */
package robot.control.idea.lang


class RocFileType extends AbstractRocFileType {
	public static final RocFileType INSTANCE = new RocFileType()
	
	new() {
		super(RocLanguage.INSTANCE)
	}
}
