/**
 * generated by Xtext 2.10.0
 */
package robot.control.idea.completion;

import robot.control.idea.completion.AbstractRocCompletionContributor;

@SuppressWarnings("all")
public class RocCompletionContributor extends AbstractRocCompletionContributor {
  public RocCompletionContributor() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe constructor RocCompletionContributor(AbstractXtextLanguage) refers to the missing type AbstractXtextLanguage");
  }
  
  public RocCompletionContributor(final /* AbstractXtextLanguage */Object lang) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(AbstractXtextLanguage) is undefined");
  }
}
