/**
 * generated by Xtext 2.10.0
 */
package robot.control.roc;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link robot.control.roc.Action#getActionHolder <em>Action Holder</em>}</li>
 *   <li>{@link robot.control.roc.Action#getIntensity <em>Intensity</em>}</li>
 * </ul>
 *
 * @see robot.control.roc.RocPackage#getAction()
 * @model
 * @generated
 */
public interface Action extends EObject
{
  /**
   * Returns the value of the '<em><b>Action Holder</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Action Holder</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action Holder</em>' containment reference.
   * @see #setActionHolder(EObject)
   * @see robot.control.roc.RocPackage#getAction_ActionHolder()
   * @model containment="true"
   * @generated
   */
  EObject getActionHolder();

  /**
   * Sets the value of the '{@link robot.control.roc.Action#getActionHolder <em>Action Holder</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action Holder</em>' containment reference.
   * @see #getActionHolder()
   * @generated
   */
  void setActionHolder(EObject value);

  /**
   * Returns the value of the '<em><b>Intensity</b></em>' attribute.
   * The literals are from the enumeration {@link robot.control.roc.Intensity}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Intensity</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Intensity</em>' attribute.
   * @see robot.control.roc.Intensity
   * @see #setIntensity(Intensity)
   * @see robot.control.roc.RocPackage#getAction_Intensity()
   * @model
   * @generated
   */
  Intensity getIntensity();

  /**
   * Sets the value of the '{@link robot.control.roc.Action#getIntensity <em>Intensity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Intensity</em>' attribute.
   * @see robot.control.roc.Intensity
   * @see #getIntensity()
   * @generated
   */
  void setIntensity(Intensity value);

} // Action
