/**
 * generated by Xtext 2.10.0
 */
package robot.control.roc;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Back Forth Direction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link robot.control.roc.BackForthDirection#getBack <em>Back</em>}</li>
 *   <li>{@link robot.control.roc.BackForthDirection#getForth <em>Forth</em>}</li>
 * </ul>
 *
 * @see robot.control.roc.RocPackage#getBackForthDirection()
 * @model
 * @generated
 */
public interface BackForthDirection extends EObject
{
  /**
   * Returns the value of the '<em><b>Back</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Back</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Back</em>' attribute.
   * @see #setBack(String)
   * @see robot.control.roc.RocPackage#getBackForthDirection_Back()
   * @model
   * @generated
   */
  String getBack();

  /**
   * Sets the value of the '{@link robot.control.roc.BackForthDirection#getBack <em>Back</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Back</em>' attribute.
   * @see #getBack()
   * @generated
   */
  void setBack(String value);

  /**
   * Returns the value of the '<em><b>Forth</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Forth</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Forth</em>' attribute.
   * @see #setForth(String)
   * @see robot.control.roc.RocPackage#getBackForthDirection_Forth()
   * @model
   * @generated
   */
  String getForth();

  /**
   * Sets the value of the '{@link robot.control.roc.BackForthDirection#getForth <em>Forth</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Forth</em>' attribute.
   * @see #getForth()
   * @generated
   */
  void setForth(String value);

} // BackForthDirection
