/**
 * generated by Xtext 2.10.0
 */
package robot.control.roc;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Directed Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link robot.control.roc.DirectedAction#getActionName <em>Action Name</em>}</li>
 *   <li>{@link robot.control.roc.DirectedAction#getDirection <em>Direction</em>}</li>
 * </ul>
 *
 * @see robot.control.roc.RocPackage#getDirectedAction()
 * @model
 * @generated
 */
public interface DirectedAction extends EObject
{
  /**
   * Returns the value of the '<em><b>Action Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Action Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action Name</em>' containment reference.
   * @see #setActionName(EObject)
   * @see robot.control.roc.RocPackage#getDirectedAction_ActionName()
   * @model containment="true"
   * @generated
   */
  EObject getActionName();

  /**
   * Sets the value of the '{@link robot.control.roc.DirectedAction#getActionName <em>Action Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action Name</em>' containment reference.
   * @see #getActionName()
   * @generated
   */
  void setActionName(EObject value);

  /**
   * Returns the value of the '<em><b>Direction</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Direction</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Direction</em>' containment reference.
   * @see #setDirection(EObject)
   * @see robot.control.roc.RocPackage#getDirectedAction_Direction()
   * @model containment="true"
   * @generated
   */
  EObject getDirection();

  /**
   * Sets the value of the '{@link robot.control.roc.DirectedAction#getDirection <em>Direction</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Direction</em>' containment reference.
   * @see #getDirection()
   * @generated
   */
  void setDirection(EObject value);

} // DirectedAction
