/**
 * generated by Xtext 2.10.0
 */
package robot.control.roc;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Direction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link robot.control.roc.Direction#getUP <em>UP</em>}</li>
 *   <li>{@link robot.control.roc.Direction#getDOWN <em>DOWN</em>}</li>
 *   <li>{@link robot.control.roc.Direction#getLEFT <em>LEFT</em>}</li>
 *   <li>{@link robot.control.roc.Direction#getRIGHT <em>RIGHT</em>}</li>
 * </ul>
 *
 * @see robot.control.roc.RocPackage#getDirection()
 * @model
 * @generated
 */
public interface Direction extends EObject
{
  /**
   * Returns the value of the '<em><b>UP</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>UP</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>UP</em>' attribute.
   * @see #setUP(String)
   * @see robot.control.roc.RocPackage#getDirection_UP()
   * @model
   * @generated
   */
  String getUP();

  /**
   * Sets the value of the '{@link robot.control.roc.Direction#getUP <em>UP</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>UP</em>' attribute.
   * @see #getUP()
   * @generated
   */
  void setUP(String value);

  /**
   * Returns the value of the '<em><b>DOWN</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>DOWN</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>DOWN</em>' attribute.
   * @see #setDOWN(String)
   * @see robot.control.roc.RocPackage#getDirection_DOWN()
   * @model
   * @generated
   */
  String getDOWN();

  /**
   * Sets the value of the '{@link robot.control.roc.Direction#getDOWN <em>DOWN</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>DOWN</em>' attribute.
   * @see #getDOWN()
   * @generated
   */
  void setDOWN(String value);

  /**
   * Returns the value of the '<em><b>LEFT</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>LEFT</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>LEFT</em>' attribute.
   * @see #setLEFT(String)
   * @see robot.control.roc.RocPackage#getDirection_LEFT()
   * @model
   * @generated
   */
  String getLEFT();

  /**
   * Sets the value of the '{@link robot.control.roc.Direction#getLEFT <em>LEFT</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>LEFT</em>' attribute.
   * @see #getLEFT()
   * @generated
   */
  void setLEFT(String value);

  /**
   * Returns the value of the '<em><b>RIGHT</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>RIGHT</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>RIGHT</em>' attribute.
   * @see #setRIGHT(String)
   * @see robot.control.roc.RocPackage#getDirection_RIGHT()
   * @model
   * @generated
   */
  String getRIGHT();

  /**
   * Sets the value of the '{@link robot.control.roc.Direction#getRIGHT <em>RIGHT</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>RIGHT</em>' attribute.
   * @see #getRIGHT()
   * @generated
   */
  void setRIGHT(String value);

} // Direction
