/*
 * generated by Xtext 2.10.0
 */
package robotcontrol.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import robotcontrol.parser.antlr.internal.InternalRocParser;
import robotcontrol.services.RocGrammarAccess;

public class RocParser extends AbstractAntlrParser {

	@Inject
	private RocGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRocParser createParser(XtextTokenStream stream) {
		return new InternalRocParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public RocGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RocGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
