/**
 * generated by Xtext 2.10.0
 */
package robotcontrol.roc;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Back Forth Directed Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link robotcontrol.roc.BackForthDirectedAction#getHead <em>Head</em>}</li>
 * </ul>
 *
 * @see robotcontrol.roc.RocPackage#getBackForthDirectedAction()
 * @model
 * @generated
 */
public interface BackForthDirectedAction extends EObject
{
  /**
   * Returns the value of the '<em><b>Head</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Head</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Head</em>' attribute.
   * @see #setHead(String)
   * @see robotcontrol.roc.RocPackage#getBackForthDirectedAction_Head()
   * @model
   * @generated
   */
  String getHead();

  /**
   * Sets the value of the '{@link robotcontrol.roc.BackForthDirectedAction#getHead <em>Head</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Head</em>' attribute.
   * @see #getHead()
   * @generated
   */
  void setHead(String value);

} // BackForthDirectedAction
