/**
 * generated by Xtext 2.10.0
 */
package robotcontrol.roc;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Left Right Direction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link robotcontrol.roc.LeftRightDirection#getLeft <em>Left</em>}</li>
 *   <li>{@link robotcontrol.roc.LeftRightDirection#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see robotcontrol.roc.RocPackage#getLeftRightDirection()
 * @model
 * @generated
 */
public interface LeftRightDirection extends EObject
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' attribute.
   * @see #setLeft(String)
   * @see robotcontrol.roc.RocPackage#getLeftRightDirection_Left()
   * @model
   * @generated
   */
  String getLeft();

  /**
   * Sets the value of the '{@link robotcontrol.roc.LeftRightDirection#getLeft <em>Left</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' attribute.
   * @see #getLeft()
   * @generated
   */
  void setLeft(String value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Right</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' attribute.
   * @see #setRight(String)
   * @see robotcontrol.roc.RocPackage#getLeftRightDirection_Right()
   * @model
   * @generated
   */
  String getRight();

  /**
   * Sets the value of the '{@link robotcontrol.roc.LeftRightDirection#getRight <em>Right</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' attribute.
   * @see #getRight()
   * @generated
   */
  void setRight(String value);

} // LeftRightDirection
