/**
 * generated by Xtext 2.10.0
 */
package robotcontrol.roc;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Motion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link robotcontrol.roc.Motion#getAction <em>Action</em>}</li>
 *   <li>{@link robotcontrol.roc.Motion#getDuration <em>Duration</em>}</li>
 *   <li>{@link robotcontrol.roc.Motion#getDurationUnit <em>Duration Unit</em>}</li>
 * </ul>
 *
 * @see robotcontrol.roc.RocPackage#getMotion()
 * @model
 * @generated
 */
public interface Motion extends EObject
{
  /**
   * Returns the value of the '<em><b>Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Action</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' containment reference.
   * @see #setAction(Action)
   * @see robotcontrol.roc.RocPackage#getMotion_Action()
   * @model containment="true"
   * @generated
   */
  Action getAction();

  /**
   * Sets the value of the '{@link robotcontrol.roc.Motion#getAction <em>Action</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' containment reference.
   * @see #getAction()
   * @generated
   */
  void setAction(Action value);

  /**
   * Returns the value of the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Duration</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Duration</em>' attribute.
   * @see #setDuration(String)
   * @see robotcontrol.roc.RocPackage#getMotion_Duration()
   * @model
   * @generated
   */
  String getDuration();

  /**
   * Sets the value of the '{@link robotcontrol.roc.Motion#getDuration <em>Duration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Duration</em>' attribute.
   * @see #getDuration()
   * @generated
   */
  void setDuration(String value);

  /**
   * Returns the value of the '<em><b>Duration Unit</b></em>' attribute.
   * The literals are from the enumeration {@link robotcontrol.roc.DurationUnit}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Duration Unit</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Duration Unit</em>' attribute.
   * @see robotcontrol.roc.DurationUnit
   * @see #setDurationUnit(DurationUnit)
   * @see robotcontrol.roc.RocPackage#getMotion_DurationUnit()
   * @model
   * @generated
   */
  DurationUnit getDurationUnit();

  /**
   * Sets the value of the '{@link robotcontrol.roc.Motion#getDurationUnit <em>Duration Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Duration Unit</em>' attribute.
   * @see robotcontrol.roc.DurationUnit
   * @see #getDurationUnit()
   * @generated
   */
  void setDurationUnit(DurationUnit value);

} // Motion
