/**
 * generated by Xtext 2.10.0
 */
package robotcontrol.roc;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Speed</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link robotcontrol.roc.Speed#getSLOWEST <em>SLOWEST</em>}</li>
 *   <li>{@link robotcontrol.roc.Speed#getSLOW <em>SLOW</em>}</li>
 *   <li>{@link robotcontrol.roc.Speed#getNORMAL <em>NORMAL</em>}</li>
 *   <li>{@link robotcontrol.roc.Speed#getFAST <em>FAST</em>}</li>
 *   <li>{@link robotcontrol.roc.Speed#getFULL <em>FULL</em>}</li>
 * </ul>
 *
 * @see robotcontrol.roc.RocPackage#getSpeed()
 * @model
 * @generated
 */
public interface Speed extends EObject
{
  /**
   * Returns the value of the '<em><b>SLOWEST</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>SLOWEST</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>SLOWEST</em>' attribute.
   * @see #setSLOWEST(String)
   * @see robotcontrol.roc.RocPackage#getSpeed_SLOWEST()
   * @model
   * @generated
   */
  String getSLOWEST();

  /**
   * Sets the value of the '{@link robotcontrol.roc.Speed#getSLOWEST <em>SLOWEST</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>SLOWEST</em>' attribute.
   * @see #getSLOWEST()
   * @generated
   */
  void setSLOWEST(String value);

  /**
   * Returns the value of the '<em><b>SLOW</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>SLOW</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>SLOW</em>' attribute.
   * @see #setSLOW(String)
   * @see robotcontrol.roc.RocPackage#getSpeed_SLOW()
   * @model
   * @generated
   */
  String getSLOW();

  /**
   * Sets the value of the '{@link robotcontrol.roc.Speed#getSLOW <em>SLOW</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>SLOW</em>' attribute.
   * @see #getSLOW()
   * @generated
   */
  void setSLOW(String value);

  /**
   * Returns the value of the '<em><b>NORMAL</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>NORMAL</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>NORMAL</em>' attribute.
   * @see #setNORMAL(String)
   * @see robotcontrol.roc.RocPackage#getSpeed_NORMAL()
   * @model
   * @generated
   */
  String getNORMAL();

  /**
   * Sets the value of the '{@link robotcontrol.roc.Speed#getNORMAL <em>NORMAL</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>NORMAL</em>' attribute.
   * @see #getNORMAL()
   * @generated
   */
  void setNORMAL(String value);

  /**
   * Returns the value of the '<em><b>FAST</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>FAST</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>FAST</em>' attribute.
   * @see #setFAST(String)
   * @see robotcontrol.roc.RocPackage#getSpeed_FAST()
   * @model
   * @generated
   */
  String getFAST();

  /**
   * Sets the value of the '{@link robotcontrol.roc.Speed#getFAST <em>FAST</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>FAST</em>' attribute.
   * @see #getFAST()
   * @generated
   */
  void setFAST(String value);

  /**
   * Returns the value of the '<em><b>FULL</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>FULL</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>FULL</em>' attribute.
   * @see #setFULL(String)
   * @see robotcontrol.roc.RocPackage#getSpeed_FULL()
   * @model
   * @generated
   */
  String getFULL();

  /**
   * Sets the value of the '{@link robotcontrol.roc.Speed#getFULL <em>FULL</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>FULL</em>' attribute.
   * @see #getFULL()
   * @generated
   */
  void setFULL(String value);

} // Speed
