/**
 * generated by Xtext 2.10.0
 */
package robot.control.idea;

@SuppressWarnings("all")
public class RocIdeaSetup /* implements ISetup  */{
  @Override
  public Object createInjectorAndDoEMFRegistration() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field EcoreGlobalRegistries is undefined"
      + "\nThe method createInjector() from the type RocStandaloneSetupIdea refers to the missing type Object"
      + "\nensureInitialized cannot be resolved");
  }
}
