/**
 * generated by Xtext 2.10.0
 */
package robot.control.idea;

@SuppressWarnings("all")
public class RocStandaloneSetupIdea /* implements RocStandaloneSetupGenerated  */{
  @Override
  public Object createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nRocRuntimeModule cannot be resolved."
      + "\nThe method or field Modules2 is undefined"
      + "\nThe method or field Guice is undefined"
      + "\nmixin cannot be resolved"
      + "\ncreateInjector cannot be resolved");
  }
}
