/*
 * generated by Xtext 2.10.0
 */
package robot.control.idea.lang.pom;

import org.eclipse.xtext.idea.pom.AbstractXtextPomDeclarationSearcher;
import robot.control.idea.lang.RocLanguage;

public class RocPomDeclarationSearcher extends AbstractXtextPomDeclarationSearcher {

	public RocPomDeclarationSearcher() {
		super(RocLanguage.INSTANCE);
	}
}
