/**
 * generated by Xtext 2.10.0
 */
package robot.control.idea.highlighting;

import robot.control.idea.highlighting.RocBaseColorSettingsPage;

@SuppressWarnings("all")
public class RocColorSettingsPage extends RocBaseColorSettingsPage {
}
